---
permalink: faq/faq-general-insight-questions.html 
sidebar: sidebar 
keywords: redhat,Linux 
summary: 本常见问题解答解答解答了有关OnCommand Insight 的常见问题。 
---
= 一般问题
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本常见问题解答解答解答了有关OnCommand Insight 的常见问题。



== OnCommand Insight (OCI)是何时推出的？

OCI是目前业内最成熟的基础架构监控产品之一、已有十年的积极开发。SANscreen 名称以前称为Onaro或SANscreen 、加入OnCommand 产品组合套件时发生了更改、现在称为OnCommand Insight 、更常见的是Insight或OCI。



== 在我的环境中部署OCI需要多长时间？

OCI只是一个软件下载。软件安装在两个专用虚拟或物理服务器上。典型安装只需 2 小时即可完成，并且几乎会立即开始提供清单，容量和性能数据。任何其他性能和最佳实践策略，用户标注和成本感知设置都需要进行额外的规划讨论。



== OCI是否需要代理、收集器或探针？

OCI 100%无代理、不需要使用代理、分路器或探针。所有设备发现均为只读，带外和通过 IP 执行。



== OCI如何发现并连接到设备？

OCI设置可利用数据中心环境中通常已存在的本机API和协议、而无需代理或探测。SSH ， HTTP ， SMIS 和 CLI 只是其中的几个示例。如果已存在设备元素管理器(例如EMC的Unisphere)、OCI将与Element管理器通信以捕获现有环境数据。大多数设备发现只需要 IP 地址以及只读用户名和密码。这些设备发现可以是"`一对多`"、例如OCI的VMware数据源。通过发现VMware vCenter、OCI进而发现其所有ESXi主机及其关联虚拟机、所有这些主机都使用一个IP地址和凭据。



== OCI是否需要专业服务？这些功能是否可用？它们提供哪些功能？

对于规模适中的环境、我们建议使用专业服务进行部署、配置和集成、并提供各种自定义报告和数据验证功能。与OCI团队和客户接洽经理进行简短讨论、有助于确定哪些服务最能让您受益。



== OCI发布更新新功能和改进功能的频率如何？

多个版本的OCI均提供产品更新和服务包。主要或次要版本通常每隔几个月提供一次，服务包包括新设备支持和固件发布频率更高。这两种方法均可从 support.netapp.com 下载站点获得。某些更新会自动推送到OCI软件中、例如、制造商经常推出的新磁盘型号。此外、在修复或更新开发之后、可以立即在站点上修补OCI数据源设备收集。



== OCI管理团队如何确定新数据源请求的优先级？

OCI的产品管理团队会主动跟踪所有客户增强功能和互操作性功能请求(IFR)。每个请求都经过详细评估，可行性评估，并根据客户需求和整体战略业务影响确定优先级。一旦被接受，请求将根据工作级别进行规模估算，并计划在将来进行开发。由于OCI开发过程非常灵活、因此可以在定期计划的发布周期之外提供新的数据源。NetApp 客户代表可以协助您处理客户咨询和代表您提交新请求。可以在站点上修补数据源、而无需升级OCI。



== 我的公司完全在 Linux 上运行。OCI是否可以在Linux上运行？

是的、OCI支持多种Linux和Windows。请注意、Cognos (OCI与数据仓库结合使用的IBM报告工具)仅在Windows上受支持、因此、如果您使用OCI进行报告、则需要在Windows服务器上运行报告工具。《OCI安装指南》列出了每个OCI组件的服务器要求和支持的操作系统。



== OCI是否适用于不能访问Internet的安全环境？

是的、OCI被全球排名前10位的财富500强企业以及领先的银行、医疗保健、研究和政府机构所使用。OCI支持美国军用通用访问卡(CAC)、并为地理位置分散或防火墙严重的环境提供解决方案。



== 我一直听说 OnCommand 统一管理器（ OCUM ）是 cDOT 的管理解决方案。您能否帮助我了解为什么还要使用OCI？

OnCommand Unified Manager在存储阵列的"`d`管理"层运行、可对集群模式Data ONTAP (cDOT)阵列及其集群互连进行深入的意外事件和基于事件的分析。OCI提供了由7-模式、集群模式Data ONTAP 和其他第三方阵列组成的内部环境和全球分散环境的整体视图。从 VM 到磁盘轴，其端到端可见性支持对容量，性能和成本建模进行历史趋势分析和预测，从而为数据中心管理提供主动式服务质量方法。



== 自动化店面中提到的OnCommand Insight 二级ETL是什么？

某些OnCommand Insight 自动化StoreFront报告下载中提及的"二级ETL"要求是指为填充到OnCommand Insight 数据仓库中的人员开发的专业服务实施、用于调用所捕获数据的额外提取、转换和加载(ETL)。

二级 ETL 流程的主要目的是预取 " 批量 " 数据，以便更快地生成更复杂的报告，或者按计划每天运行报告。

此二级ETL是对OnCommand Insight 数据仓库管理指南中详细介绍的建议的"每天一次"ETL的补充。

NetApp专业服务有资格配置二级ETL脚本、以避免影响现有OnCommand Insight 报告计划、自动备份、可扩展性或其他系统性能活动。有关追加信息在 ETL 脚本编写或数据验证方面的需求，请联系您的 NetApp 销售代表，并讨论 NetApp 的专业服务如何为您提供帮助。
