---
permalink: faq/faq-anomaly-detection.html 
sidebar: sidebar 
keywords:  
summary: 本常见问题解答解答解答了有关OnCommand Insight 异常检测的常见问题。 
---
= 异常检测
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本常见问题解答解答解答了有关OnCommand Insight 异常检测的常见问题。



== 什么是异常？

异常是指IOPS、延迟、利用率、缓冲区到缓冲区信用值和CPU中不符合先前观察到的和预期模式的性能更改事件。OCI异常检测面向为应用程序提供服务的应用程序基础架构、以查找处理模式和行为的变化。这些周期性处理模式包括业务运营时间和周末工作负载性能的历史"`ebbs and flows`"。OCI中的异常检测引擎使用机器学习智能来建立"`normal`"基线模式、并检测定义的应用程序何时偏离其预期行为。



== 异常检测在OCI中的工作原理是什么？

OCI `的异常检测是一种主动监控方法、它利用基于历史信息的机器学习智能。它能够比传统阈值更快地检测到新兴性能异常、因此管理员可以在应用程序SLO或数据中心服务受到影响之前有更多时间讨论、规划和缓解问题。

Insight可发现并自动映射支持应用程序的整个基础架构堆栈、从计算资源开始、通过交换机网络结构、然后向下映射到存储资源。OCI收集关键性能计数器、包括IOPS、延迟、节点信息、存储池利用率、虚拟机管理程序CPU、 每个资源的BB信用为零、然后将该数据馈送到异常检测引擎、以用于应用程序异常分析。异常结果每小时更新两次、并可在应用程序信息板、应用程序登录页面和查询表小工具上查看。异常评分按资源和计数器进行、并为整个应用程序基础架构提供整体重要性得分。



== 哪些版本的OCI支持异常检测？

OCI 7.2及更高版本支持异常检测。



== OCI可以为多少个应用程序启用异常检测？

OCI支持监控多达48个业务关键型应用程序。



== 可以部署多少个异常检测引擎(ADES)？

每个OCI操作服务器一个异常检测引擎。



== 如果我有48个以上的应用程序、是否可以部署其他异常检测引擎？

是的、目前OCI支持为每个OCI服务器配对一个异常检测引擎。在多OCI服务器环境中、可以"`配对`"的方式部署其他异常检测引擎和OCI操作服务器。如果启用了异常检测功能、则每个服务器只能查看其应用程序。



== 应用程序集群/组的大小是否存在扩展限制？

使用Insight异常检测功能实现最佳操作和扩展的OCI工程一般准则如下：每个Insight服务器支持一个异常检测引擎。在OCI中最多可以监控48个应用程序。应用程序基础架构最多可包含4000个对象。资源不足会降低整体规模。



== 异常检测需要哪些OCI许可证？

异常检测分析需要发现和执行许可证。



== 检测异常并查看结果需要多长时间？

启用应用程序监控后、异常评分结果将在2-3小时内显示。



== 在操作使用结果之前、我应等待多长时间？

异常检测引擎结果的质量和准确性会随着时间(周、月、季度等)的推移而提高。周期性评估(周期)通常在第三周左右开始。对于持续时间较长的模式(例如每月)、需要在调整异常分数之前、引擎观察重复事件。



== 异常检测引擎将其学习内容保留多长时间？

异常检测引擎存储学习信息的方式效率很高。可以在数月内对对象的异常行为进行统计学习。在Insight中、典型数据集没有常见的"`re`"。异常检测引擎可`s并存储一段时间内确定为"`有意义"的数据、并在必要时淘汰不重要的数据。这种机制可显著延长学习时间、并减少存储数据所需的资源和执行分析的时间



== 如果我今天启用异常检测、它能否告诉我上周发生了哪些异常？

不会、初始化异常检测时、Insight服务器会从Insight服务器加载任何现有性能数据、以提高异常检测引擎对受监控应用程序及其基础架构的了解。载入的"`预先存在的`"性能数据不会出现异常。只有在根据预先存在的数据进行分析时、才会报告新传入数据的异常情况。新检测到的异常将在短短几小时内开始显示。



== 如何计算异常分数？

每个应用程序异常分数均通过各个资产分数的汇总计算得出。异常检测引擎利用30多种复杂算法和公式来确定异常情况并获得相应的分数。用户可以将这种类型的分析评分技术与类似的医学评分进行比较、例如、由多种变量和测量结果(重量、年龄、高度、密度等)构成的身体质量指数(BMI)得分。



== 每个蓝色条表示什么？

每个包含3个条的块表示一个资源及其异常重要性范围。蓝条越多、观察到的行为变化越大。单击这些块可显示异常的重要性、各个资源和计数器。



== 为什么单个资源得分与总应用程序得分不符？

每个资源都会根据观察到的行为差异单独进行评分。单个资源评分的重要性在应用程序总评分中确实有一定影响、但也可能包括其他分析和数学因素。



== 是否可以配置异常检测以监控分配了标注的业务实体或对象？

目前、只能在定义的应用程序上启用异常检测。可以对可分配给应用程序的任何对象(VM、虚拟机管理程序、服务器、卷和内部卷)进行分组和监控。



== OCI是否可以为异常分数较高提供通知？

可以、您可以根据应用程序的异常分数创建应用程序性能策略。如果超过策略中定义的阈值、则会触发警报、向您通知应用程序中资源的相关问题。



== 在应用程序上关闭异常检测时会发生什么情况？

从异常检测引擎中清除应用程序基础架构的所有已学习(历史异常)信息。所有异常检测结果都会从Insight操作数据库中清除。



== 何时应使用静态阈值？

静态阈值非常适合用于针对基础架构资源限制发出最佳实践警报以及确定事件持续时间。它们还有助于管理服务级别、并针对各种错误计数器指标发出警报、例如链路重置、类3丢弃和失去同步。



== 有哪些计划将其他指标纳入异常检测？

随着新的统计数据、用户反馈和产品改进的出现、异常机器学习模式和算法将继续得到改进或调整。



== 异常结果在数据仓库(DWH)中是否可用？

当前的异常结果不会发送(ETL-ed)到OCI数据仓库。用户可以在OCI应用程序登录页面或用户定义的查询表小工具中找到结果。
