---
permalink: faq/faq-insight-licensing.html 
sidebar: sidebar 
keywords:  
summary: 有关OnCommand Insight 许可的常见问题解答。 
---
= OnCommand Insight 许可
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
有关OnCommand Insight 许可的常见问题解答。



== OCI许可概述

OCI按容量获得许可。客户必须为要启用的每个模块购买许可证：

*发现*是保证、执行和计划的前提条件、不能单独提供。发现按TB受管容量许可。

*保证*以TB受管容量(作为一个单位对所有存储基础架构(FC、NAS、iSCSI、FCoE)进行许可。

*执行*按TB受管容量进行许可。

*计划*按TB受管容量进行许可。

"`m容量`"是指格式化前物理磁盘、虚拟磁盘和磁带的原始容量。这适用于Insight发现的所有存储、包括内部和云中的存储。

大多数数据源都考虑磁盘原始基础2容量。不考虑磁盘角色、例如备用磁盘、未分配磁盘或RAID磁盘。

有两种类型的Insight许可证可用：*永久许可证*和*订阅*。

通过*永久许可证*、您可以根据适用的许可证条款无限期地使用所获得的软件的特定版本/版本。如果您购买了软件支持计划(SSP)、则在根据NetApp 支持站点 支持服务条款提供更新时、NetApp可以通过NetApp提供对商用软件更新的访问权限。此外、NetApp还可以访问由NetApp技术支持中心确定的特殊修补程序。

*订阅*是软件的固定期限许可证、授予以下权利：

* 在受适用许可证条款约束的情况下、仅在有限期限内(通常为12个月)使用内部软件
* 在此期限内获得软件支持(以前称为SSP)
* 实际上、如果有任何版本可供使用、则被许可人可以使用最新的商业版本、版本或更新、并可获得对软件的支持


在每个固定期限(通常为12个月)结束时、许可证可以再续订一个固定期限(通常为12个月)。如果未续订许可证、则被许可人将不再有权使用该软件、也不再有权享受SSP的优势、并且被许可人必须销毁该软件的所有副本。



== 有关OCI许可证模块的更多信息

OCI具有4个核心许可证模块、可满足当今数据中心环境的需求。这些模块包括*发现、执行、保证和计划*。Discover是基本模块、所有其他模块购买都需要使用它。

通过*发现*模块、OCI可以找到数据中心中的资产并动态映射设备服务路径。提供了容量、供应商信息、型号、固件和序列号等信息。

*执行*是OCI的性能收集模块。Perform可捕获IOPS、吞吐量、延迟以及CPU和内存信息、并提供其他分析功能。

*保证*面向光纤通道环境和效率技术。它有助于识别和管理光纤通道和iSCSI环境中的风险。此外、Assure还有助于了解有关屏蔽、映射和分区服务路径条目的标识、映射和警报以及网络结构冗余、交换机跃点、扇出比率和精简配置等效率最佳实践策略的信息。

通过*计划*、可以在混合内部部署和全球分布的数据中心环境中发现和预测计算、网络结构和各种类型的存储(cDOT、7-模式、第三方)的趋势。它可以延长保留时间。数据仓库包含一个内置智能、可用于编写报告、并避免在企业共享存储环境中重复计算指标。它可以生成和计划"即装即用`"的产品化报告、或者使用其`拖放``集成报告创作工具创建您自己的报告。
