---
permalink: faq/faq-integrating-insight-and-third-party-tools.html 
sidebar: sidebar 
keywords:  
summary: 本常见问题解答解答解答了有关OnCommand Insight 与其他工具集成的常见问题。 
---
= 将Insight与其他工具集成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本常见问题解答解答解答了有关OnCommand Insight 与其他工具集成的常见问题。



== OCI是否可以与其他工具集成？有哪些集成点可用？

是的、OCI是一种可扩展(广泛开放)的解决方案 、支持与第三方业务流程、业务管理、变更控制和服务单系统以及自定义CMDB集成。OCI完全发布的RESTful API和开放式MySQL数据库的主要集成点可以轻松高效地移动数据、并允许用户无缝访问其数据。

Insight基于Swagger的API文档位于产品*(？)下 帮助> REST API文档*。



== 什么是Insight BMC Connector？

适用于BMC的OnCommand Insight 连接器集成了OnCommand Insight 数据仓库(DWH)和BMC Atrium配置管理数据库(CMDB)。适用于BMC的Insight Connector可映射有关网络存储系统(例如、存储单元、主机存储服务、VS存储服务和VM存储服务)的物理和逻辑存储数据及其与设备(主机、存储交换机、 和磁带)并将其作为配置项和关系导入到BMC CMDB中。有关适用于BMC的OnCommand Insight 连接器的详细信息、请参见NetApp 支持站点。



== OCI是否可与SCOM或VROP配合使用？

是的、OCI是对许多业务管理解决方案的补充、被视为数据中心存储、计算、虚拟机管理程序和网络结构信息的权威来源。OCI客户利用OCI的RESTful API和可扩展MySQL数据库来增强BMC的补救、ServiceNow、SCOM、Vrops和Splunk等众多应用程序、 举几个例子。OCI可通过从几乎任何记录源导入信息和/或将捕获的环境指标发送到常用的第三方监控、计费、CMDB计费和业务流程系统来扩展集成。



== OCI是否可以与我已使用或正在考虑使用的云服务配合使用？

是的、OCI对传统内部部署和灵活的混合云环境进行管理、可以在根据业务服务需求确定最佳、最经济高效的平台时提供可见性。OCI可用于迁移前和迁移后分析、有助于确定适合云的工作负载。要选择适当的云服务、必须具备历史容量趋势、性能和成本。利用OCI的I/O密度和其他指标举办的服务设计研讨会还可以帮助您解决问题解答 问题、例如您是否优化了环境以及云是否合理。OCI通过支持NetApp私有存储、Cloud ONTAP 、Amazon S3和OpenStack KVM继续扩大其覆盖范围。OCI继续在NetApp的云管理营销活动中发挥着重要作用、尤其是在对容量规划、性能、服务质量和成本分摊的了解非常重要的领域。



== OCI是否可以在我们的意外事件管理解决方案 中打开意外事件？

可以、OCI违规事件可以通过SNMP作为陷阱或通过系统日志触发并发送到服务器、某些事件可以通过RESTful API发送。提供的事件中包含的详细信息可通过许多第三方意外事件管理和服务单解决方案来解释。



== 您能否为业务单位或部门分配资源？

是的、OCI采用了一种称为标注的元数据标记方法。可以将业务单位、业务部门、租户和项目分配给数据中心资源、以便围绕资产、容量规划、故障排除和报告提供更丰富的业务环境。



== OCI是否与工作流自动化器(WFA)配合使用？

OCI与第三方CMDB、计费和流程编排技术的集成功能是其成功的关键价值、WFA也不例外。NetApp的专业服务已成功完成许多与WFA工作流和OCI的集成。



== 性能数据的OCI保留时间有多长时间？

OCI服务器可提供90天近乎实时的性能以及当前(时间点)清单(逻辑和物理构造)。

OCI性能轮询间隔可由用户配置。对于大多数供应商、存储性能通常每5分钟配置一次。每天、性能/清单数据都会发送到OCI数据仓库(DWH)、以便进行长期历史和预测报告。DWH会将此数据转换为汇总数据(每小时、每天、每月汇总数据)。我们能够跟踪"`变更`"、例如存储/计算/网络结构配置/映射的受监控环境历史记录、目前没有定义的限制。

数据仓库会根据数据集市和数据粒度保留历史数据。



== 是否有任何性能规划报告？

是的、OCI提供了多个报告、而我们的专业服务目录也根据使用情形提供了许多其他报告。数据仓库模块还附带了一套Cognos报告创作工具、用户可以使用这些工具创建自己的报告。
