---
permalink: faq/faq-performance-troubleshooting.html 
sidebar: sidebar 
keywords:  
summary: 本常见问题解答解答解答了有关OnCommand Insight 性能故障排除的常见问题。 
---
= 性能故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本常见问题解答解答解答了有关OnCommand Insight 性能故障排除的常见问题。



== 如何创建环境中所有耗用资源的列表？

OCI的关联分析有助于确定指定服务路径中资源的耗用和降级情况。在查看每个对象时，系统会实时执行关联功能生成的分析。通过提供的分析，可以大大减少对性能问题进行故障排除和识别根发生原因所需的时间。要发现资源耗用或已降级，首先需要了解所定义的性能策略生成的违规情况。OCI的异常检测功能也可用作一种更主动的方法、用于在应用程序基础架构资源耗竭或降级后避免其造成服务中断。使用最新查询功能的小工具和信息板均有助于筛选，排序和可视化 IOPS （ Greedy ），利用率或延迟高于预期的资源。



== OCI能否提供一个位置来诊断性能问题？

是的。OCI中的性能故障排除方法有多种。OCI可以采用多种警报方法。通常使用 SNMP ，系统日志和电子邮件警报。通过电子邮件发送的警报、用户可以快速单击并启动到OCI中受影响的资源。管理员可以通过全局搜索窗口键入资源名称来开始分析情况。

通过OCI的违规信息板、用户可以根据事件数量、持续时间和一天中的时间确定工作的优先级。各种警报类型的示例包括延迟、IOPS、利用率、严重性、业务单位甚至关联的应用程序。

OCI的关联分析可帮助管理员比较与受影响资源关联的对象、并确定其对IOPS、延迟、利用率、CPU和BB信用的影响。

OCI在异常检测和以太网监控方面的最新进步提供了一种更积极主动的方法、可以在资源异常行为发生服务中断或中断之前检测这些行为。

通过OCI的查询技术和小工具信息板、可以在面向数据中心内问题区域的有组织视图中精确定位具体信息。



== OCI能否帮助我从7-模式迁移到cDOT？

可以、OCI为现有工作负载需求和迁移后验证提供了宝贵的了解。OCI在当今数据中心现代化方面的作用有助于进行变更管理模拟、迁移前优化规划以及定义合适的服务层。在多供应商环境中、只需单击几下鼠标、OCI便可轻松收集数千个NFS共享和光纤通道路径的业务影响并将其关联起来。从迁移到技术更新、OCI提供了一条实现可靠、规模合适的迁移的途径、并可减少计划外服务中断。



== OCI性能监控是如何的`re时间`？

对于内部部署和混合云数据中心管理、OCI均被视为*接近实时*。虽然可以将轮询数据源配置为更频繁地进行、但大多数用户不会因对大多数设备的性能收集间隔少于5分钟而获得显著的分析优势。更频繁地收集可能会给所管理的对象和执行的分析带来不必要的负担。当然、在某些情况下、可能需要更精细的收集、幸运的是、OCI可以提供完全的灵活性、包括可配置的设备清单和性能轮询间隔、以满足您的特定数据中心环境需求。



== 为什么我的 " 总计 " 与 " 读取 " 加上 " 写入 " 不同？

在某些情况下、您可能会注意到某个计数器的_total_不等于该计数器的_reads_plus _writes_之 和。在某些情况下，可能会发生这种情况。

* IOPS *：除了读取和写入之外、存储阵列或其他资产还会处理与工作负载数据流无关的内部操作。这些操作有时称为"`s系统`"、"`metadata`"或简单的"`其他`"操作、可归结为内部进程、例如快照、重复数据删除或空间重新分配。在这些情况下、要查找给定资产的系统操作量、请从_total_ IOPS中减去_read_和_write_ IOPS的总和。" 读写 IOPS" 与数据流直接相关的总 IOPS 之和。

*延迟*：操作的总响应时间(延迟)有时可以报告为小于写入响应时间、因为总响应时间是时间加权平均值。I/O 工作负载通常包含的读取操作多于写入操作，而写入操作通常会观察到较长的延迟。例如，如果一个工作负载执行了 10 个读取操作，平均延迟为 5 毫秒，而执行了 5 个写入操作，平均延迟为 10 毫秒，则总加权平均延迟将通过读取次数乘以平均读取延迟计算得出。 加上写入次数乘以平均写入延迟，再除以 I/O 操作总数，例如（ 10 * 5 + 5 * 10 ） / （ 10 + 5 ） = 6.33 毫秒。



== 为什么OCI和OCUM显示的过量配置空间值不同？

OnCommand 统一管理器(OCUM)的"已配置"空间概念可能包括FlexVol (OnCommand Insight 内部卷)可能增长的自动增长限制。OCI"容量"不会反映这些自动增长限制。因此、在存在自动增长FlexVol的环境中、OCUM配置的总容量将超过OCI存储级别的"过量使用的容量"总计-增量将是FlexVol容量与其自动增长容量之间的差值。
