---
permalink: faq/faq-scale-and-ease-of-use.html 
sidebar: sidebar 
keywords:  
summary: 本常见问题解答解答解答了有关OnCommand Insight 扩展和易用性的常见问题。 
---
= 扩展性和易用性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本常见问题解答解答解答了有关OnCommand Insight 扩展和易用性的常见问题。



== OCI如何扩展？

OCI在互操作性方面以及在占用空间最少的情况下可获得的资产数量方面处于领先地位。OCI的核心要求使用2个虚拟或物理服务器：一个用于发现所有数据中心资产的操作服务器、一个用于其整合数据仓库以进行长期历史报告。OCI的企业覆盖范围支持数百个阵列、数万个虚拟机、100、000个光纤通道路径和10、000多个光纤通道端口、所有这些都在一个服务器实例中提供。



== 需要多少人来管理OCI应用程序？

OCI可由一人管理。但是、OCI的功能可以由业务环境中的多个角色使用、每个角色具有不同的角色、每个角色具有不同的报告、故障排除或分析需求。我们会尽一切努力最大限度地减少工具维护工作、从显示配置问题的运行状况和通知菜单到自动发现连接到网络结构的物理主机。灵活的标注可为所有类型的用户提供生态系统数据的业务环境。从存储、网络结构和虚拟化管理员到容量规划人员、业务分析师和管理人员、OCI将跨业务孤岛和技术的信息共享整合到一个管理平台中。



== OCI是否支持自定义报告？

是的。OCI可通过IBM Cognos业务智能工具提供报告、您可以使用OCI的数据仓库中收集的数据创建自己的完全自定义报告。



== 创建自定义报告的简单程度如何？

OCI报告为新用户和高级用户提供了一些功能。OCI提供了许多报告创作功能、包括"`d拖放`"报告创作功能以及基于SQL查询的报告功能、可为更高级的用户或专业服务项目提供支持。OCI的内置业务智能解决方案 (IBM Cognos)可避免重复计算容量等常见错误。借助即装即用的报告、小工具、查询和信息板、您可以根据任何人的报告要求提供相应的功能。

客户还可以从OCI社区存储中找到可下载的报告模板。



== OCI能否以"流量轻"的简单性显示性能和可用性？

是的。OCI数据仓库和报告功能支持具有颜色增强功能的报告、例如红色/黄色/绿色"`条件样式`值。最终用户和专业服务均可在报告中生成彩色字体或背景。通过OCI小工具库、可以在信息板中显示业务特定的性能指标。
