---
permalink: faq/faq-configuration-and-supported-devices.html 
sidebar: sidebar 
keywords:  
summary: 本常见问题解答解答解答了有关OnCommand Insight 配置和支持的设备的常见问题。 
---
= 配置和支持的设备
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本常见问题解答解答解答了有关OnCommand Insight 配置和支持的设备的常见问题。



== OCI是否对我的环境进行了更改？

否OCI是一个只读工具、用于收集有关您的环境的信息。OCI不会对您的资产或配置进行任何更改。



== OCI需要对我的设备进行哪些权限级别的访问？

在大多数情况下，如果设备支持只读访问，则只需进行只读访问即可。某些解决方案不允许只读访问，因此需要适当的提升权限。



== OCI收集信息的频率如何？

OCI通常每5分钟收集一次性能数据、每½小时发现一次逻辑和物理构造。OCI会根据建议的最佳实践和可扩展性设置默认轮询间隔、但允许用户完全控制这些间隔。



== OCI对我的环境有何影响？

OCI的无代理、带外和被动IP通信有助于最大限度地减少设置、维护以及对数据中心生态系统的影响。OCI的性能开发团队采取了一些重要措施、可以最大限度地减少在监控性能本身的活动中对数据中心性能产生的任何影响。在正常操作环境中，影响可忽略不计，在高利用率或性能低下的技术平台中，影响可以宽松或收紧。有关详细信息、请参见《OnCommand Insight 安装指南》。



== 如何列出OCI中的所有主机/VM？

OCI对小工具和查询列表功能的补充、可用于为数据中心资产提供清单模式列表。虚拟机列表直至磁盘轴，以及之间的大量构造均可用于查询，小工具，信息板和数据仓库报告，并可通过 RESTful API 进行访问。



== OCI是否为相关的非虚拟机管理程序主机(即物理服务器)提供了相同类型的支持？

VMware等虚拟机管理程序可提供有关ESXi主机及其关联虚拟机(VM)的详细信息。对于物理服务器、OCI最多可收集主机HBA的指标。OCI采用一种独特的方法、通过这种方法、它可以使用正在申请专利的技术发现物理服务器。发现存储和 / 或交换机后，物理服务器的主机名包含在网络结构别名信息中。OCI会选择这些主机名、并在DNS中将其匹配、然后自动将这些主机引入OCI。这种技术可以极大地减少手动输入更新和工具清单维护的需求。



== OCI是否在异构环境中提供相同的设备度量深度(奇偶校验)？

第三方平台和供应商技术的标准化程度，通用性和命名方式各不相同。OCI会尝试将容量和性能信息规范化为一个一致的框架。某些容量和性能指标是通过设备的计数器本机提供的，例如 IOPS ，延迟和原始容量。如果未提供计数器、OCI可以尝试汇总这些值(例如、通过汇总底层卷的IOPS或容量)、如果两者均不可用、OCI将尝试通过各种计算算法来派生度量值。OCI提供了一种通用SNMP集成功能、可将当前OCI未收集的其他指标结合起来。



== OCI是否支持光纤通道交换机？

可以、除了从存储资产中收集数据之外、OCI还会从环境中的Cisco、Brocade和QLogic交换机采集清单和性能数据。



== 整个基础架构的拓扑视图是否可用？OCI是否显示"`端到端可见性`"？

可以、OCI可以动态发现和映射逻辑和物理结构、从而提供计算、网络结构、虚拟化器和后端存储的交互式端到端拓扑视图。通过拓扑图标，可以快速启动对受影响资源的导航，并有助于识别共享存储环境中的工作负载和违规。
