---
permalink: config-admin/about-oncommand-insight-anomaly-detection.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 包含机器学习异常检测分析功能、可提供对应用程序基础架构的可见性、并可在性能异常变为服务中断之前识别这些异常。 
---
= OnCommand Insight 异常检测的工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 包含机器学习异常检测分析、可提供对应用程序基础架构的可见性、并可在性能异常变为服务中断之前识别这些异常。

异常分析可帮助您确定应用程序的正常运行工作负载范围、并在性能变化超出预期水平时发出通知。应用程序异常检测引擎可载入Insight收集的性能指标、并确定应用程序基础架构中的异常情况。

您可以使用异常检测来执行以下任务：

* 确定应用程序基础架构行为的重大变化
* 在整个堆栈和多个计数器之间跟踪应用程序
* 诊断应用程序工作负载中定期重复发生的事件的发生原因
* 与使用静态阈值的性能计数器中的数据相比、可提供一组更全面的信息
* 通过端到端拓扑视图以及关注最异常行为的能力、在改进的响应模式下进行监控。


异常检测引擎使用Insight数据进行应用程序分析。首次启动监控时、分析引擎最多可以载入14天的历史性能数据。收集的数据持续数周甚至数月、可提供有关给定资源的更准确的数据。数据包括以下计数器的总数：

|===


| 对象 | 计数器 


 a| 
虚拟机
 a| 
延迟、IOPS



 a| 
虚拟机管理程序
 a| 
CPU利用率、IOPS



 a| 
边缘端口
 a| 
BB信用零



 a| 
存储节点
 a| 
延迟、利用率、IOPS



 a| 
Volume
 a| 
延迟、IOPS



 a| 
内部卷
 a| 
延迟、IOPS



 a| 
存储池
 a| 
IOPS、利用率

|===
在Insight服务器上启用性能数据归档后、异常检测引擎收集的数据将归档。请参见系统运行状况页面以确定是否已启用归档。

异常检测引擎在Insight服务器以外的单独服务器上运行。可以在物理机或虚拟机上配置它。有关详细信息、请参见适用于Windows或Linux的OnCommand Insight 安装指南。
