---
permalink: config-admin/brocade-fc-switch-firmware-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight 使用Brocade FC交换机\(SSH\)数据源发现运行Factored Operating System\(FOS\)固件4.2及更高版本的Brocade或更名交换机设备的清单。支持 FC 交换机和访问网关模式下的设备。' 
---
= Brocade FC交换机数据源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 使用Brocade FC交换机(SSH)数据源发现运行Factored Operating System (FOS)固件4.2及更高版本的Brocade或更名交换机设备的清单。支持 FC 交换机和访问网关模式下的设备。



== 术语

OnCommand Insight 从Brocade FC交换机数据源采集以下清单信息。对于Insight获取的每种资产类型、均显示了此资产最常用的术语。查看此数据源或对其进行故障排除时，请记住以下术语：

|===


| 供应商 / 型号术语 | Insight术语 


 a| 
交换机
 a| 
交换机



 a| 
Port
 a| 
Port



 a| 
虚拟网络结构，物理网络结构
 a| 
网络结构



 a| 
分区
 a| 
分区



 a| 
逻辑交换机
 a| 
逻辑交换机



 a| 
LSAN 区域
 a| 
IVR 区域

|===
[NOTE]
====
这些只是常见的术语映射、可能并不代表此数据源的所有情形。

====


== 要求

* 采集单元(本地或远程)将启动与Brocade交换机上的TCP端口22的连接、以收集清单数据。AU 还将启动与 UDP 端口 161 的连接，以收集性能数据。
* 网络结构中的所有交换机都必须具有 IP 连接。如果选中发现网络结构中的所有交换机复选框、OCI将标识网络结构中的所有交换机；但是、它需要通过IP连接到这些附加交换机才能发现它们。
* 网络结构中的所有交换机需要全局使用同一个帐户。您可以使用 PuTTY （开源终端模拟器）确认访问。
* 如果安装了Perform许可证、则端口161和162必须对网络结构中的所有交换机开放、以便进行SNMP性能轮询。
* SNMP 只读社区字符串




== Configuration

|===


| 字段 | Description 


 a| 
交换机 IP
 a| 
交换机的 IP 地址或完全限定域名



 a| 
用户名
 a| 
交换机的用户名



 a| 
Password
 a| 
交换机使用的密码



 a| 
SNMP 版本
 a| 
SNMP 版本



 a| 
SNMP 社区字符串
 a| 
用于访问交换机的 SNMP 只读社区字符串



 a| 
SNMP 用户名
 a| 
SNMP版本协议用户名(仅适用于SNMP v3)



 a| 
SNMP 密码
 a| 
SNMP版本协议密码(仅适用于SNMP v3)

|===


== 高级配置

|===


| 字段 | Description 


 a| 
网络结构名称
 a| 
数据源要报告的网络结构名称。留空以将网络结构名称报告为 WWN 。



 a| 
排除设备
 a| 
要从轮询中排除的设备 ID 的逗号分隔列表



 a| 
清单轮询间隔（分钟）
 a| 
两次清单轮询的间隔(默认值为15分钟)



 a| 
超时(秒)
 a| 
连接超时(默认为30秒)



 a| 
横幅等待超时(秒)
 a| 
SSH横幅等待超时(默认值为5秒)



 a| 
管理域处于活动状态
 a| 
选择是否使用管理域



 a| 
检索 MPR 数据
 a| 
选择此项可从多协议路由器(MPR)获取路由数据



 a| 
启用陷阱
 a| 
选择此选项可在从设备收到 SNMP 陷阱时启用采集。如果选择启用陷阱，则还必须激活 SNMP 。



 a| 
陷阱之间的最短时间（秒）
 a| 
陷阱触发的两次采集尝试之间的最短时间（默认值为 10 秒）



 a| 
发现网络结构中的所有交换机
 a| 
选择以发现网络结构中的所有交换机



 a| 
选择偏向 HBA 而不是分区别名
 a| 
选择是支持 HBA 别名还是分区别名



 a| 
性能轮询间隔（秒）
 a| 
性能轮询之间的时间间隔（默认值为 300 秒）



 a| 
SNMP 身份验证协议
 a| 
SNMP 身份验证协议（仅限 SNMP v3 ）



 a| 
SNMP 隐私协议
 a| 
SNMP隐私协议(仅限SNMP v3)



 a| 
SNMP 隐私密码
 a| 
SNMP 隐私密码（仅限 SNMP v3 ）



 a| 
SNMP 重试
 a| 
SNMP 重试尝试次数



 a| 
SNMP 超时（毫秒）
 a| 
SNMP 超时（默认为 5000 毫秒）

|===