---
permalink: config-admin/changing-oncommand-insight-internal-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: '安全策略可能要求您更改OnCommand Insight 环境中的密码。一台服务器上的某些密码存在于环境中的另一台服务器上、要求您更改这两台服务器上的密码。例如、在Insight服务器上更改"清单"用户密码时、必须与为该Insight服务器配置的Data Warehouse Server Connector上的"清单"用户密码匹配。' 
---
= 更改OnCommand Insight 内部用户密码
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
安全策略可能要求您更改OnCommand Insight 环境中的密码。一台服务器上的某些密码存在于环境中的另一台服务器上、要求您更改这两台服务器上的密码。例如、在Insight服务器上更改"`inventory`"用户密码时、必须与为该Insight服务器配置的Data Warehouse server Connector上的"`inventory`"用户密码匹配。



== 开始之前

[NOTE]
====
在更改密码之前、您应了解用户帐户的依赖关系。如果未更新所有所需服务器上的密码、则Insight组件之间的通信将失败。

====


== 关于此任务

下表列出了Insight服务器的内部用户密码、并列出了具有需要与新密码匹配的相关密码的Insight组件。

|===


| Insight服务器密码 | 所需更改 


 a| 
内部
 a| 



 a| 
采集
 a| 
LAU、RAU



 a| 
dwh_internal
 a| 
数据仓库



 a| 
主机
 a| 



 a| 
清单
 a| 
数据仓库



 a| 
root
 a| 

|===
下表列出了数据仓库的内部用户密码、并列出了具有需要与新密码匹配的相关密码的Insight组件。

|===


| 数据仓库密码 | 所需更改 


 a| 
Cognos_admin
 a| 



 a| 
dwh
 a| 



 a| 
dwh_internal (使用服务器连接器配置UI进行更改)
 a| 
Insight服务器



 a| 
dwhuser
 a| 



 a| 
主机
 a| 



 a| 
清单(使用Server Connector配置UI进行更改)
 a| 
Insight服务器



 a| 
root
 a| 

|===
*在DWH服务器连接配置用户界面中更改密码*

下表列出了LAU的用户密码、并列出了具有需要与新密码匹配的相关密码的Insight组件。

|===


| LAU密码 | 所需更改 


 a| 
采集
 a| 
Insight服务器、RAU

|===