---
permalink: config-admin/cisco-fc-switch-firmware-snmp-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight 使用Cisco FC交换机固件2.0+\(SNMP\)数据源来发现Cisco MDS光纤通道交换机以及启用了FC服务的各种Cisco Nexus FCoE交换机的清单。此外、您还可以使用此数据源发现在NPV模式下运行的多种Cisco设备型号。' 
---
= Cisco FC交换机固件(SNMP)数据源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 使用Cisco FC交换机固件2.0+(SNMP)数据源来发现Cisco MDS光纤通道交换机以及启用了FC服务的各种Cisco Nexus FCoE交换机的清单。此外、您还可以使用此数据源发现在NPV模式下运行的多种Cisco设备型号。



== 术语

OnCommand Insight 从Cisco FC交换机数据源采集以下清单信息。对于Insight获取的每种资产类型、均显示了此资产最常用的术语。查看此数据源或对其进行故障排除时，请记住以下术语：

|===


| 供应商 / 型号术语 | Insight术语 


 a| 
交换机
 a| 
交换机



 a| 
Port
 a| 
Port



 a| 
VSAN
 a| 
网络结构



 a| 
分区
 a| 
分区



 a| 
逻辑交换机
 a| 
逻辑交换机



 a| 
名称服务器条目
 a| 
名称服务器条目



 a| 
VSAN 间路由（ Inter-VSAN Routing ， IVR ）区域
 a| 
IVR 区域

|===
[NOTE]
====
这些只是常见的术语映射、可能并不代表此数据源的所有情形。

====


== 要求

* 网络结构中一个交换机或单个交换机的 IP 地址
* 机箱发现，用于启用网络结构发现
* 如果使用 SNMP V2 ，则为只读社区字符串
* 端口 161 用于访问设备
* 使用进行访问验证 `snmpwalk` 实用程序连接到交换机(请参见 `<install_path\>\bin\`）




== Configuration

|===


| 字段 | Description 


 a| 
Cisco 交换机 IP
 a| 
交换机的 IP 地址或完全限定域名



 a| 
SNMP 版本
 a| 
要获取性能、需要使用SNMP v2或更高版本



 a| 
SNMP 社区字符串
 a| 
用于访问交换机的 SNMP 只读社区字符串（不适用于 SNMP v3 ）



 a| 
用户名
 a| 
交换机的用户名（仅限 SNMP v3 ）



 a| 
Password
 a| 
交换机使用的密码（仅限 SNMPv3 ）

|===


== 高级配置

|===


| 字段 | Description 


 a| 
清单轮询间隔（分钟）
 a| 
两次清单轮询的间隔（默认为 40 分钟）



 a| 
SNMP 身份验证协议
 a| 
SNMP 身份验证协议（仅限 SNMPv3 ）



 a| 
SNMP 隐私协议
 a| 
SNMP 隐私协议（仅限 SNMPv3 ）



 a| 
SNMP 隐私密码
 a| 
SNMP隐私密码



 a| 
SNMP 重试
 a| 
SNMP 重试尝试次数



 a| 
SNMP 超时（毫秒）
 a| 
SNMP 超时（默认为 5000 毫秒）



 a| 
启用陷阱
 a| 
选择以启用陷阱。如果启用陷阱，则还必须激活 SNMP 通知。



 a| 
陷阱之间的最短时间（秒）
 a| 
陷阱触发的两次采集尝试之间的最短时间（默认值为 10 秒）



 a| 
发现所有光纤交换机
 a| 
选择以发现网络结构中的所有交换机



 a| 
排除设备
 a| 
要从轮询中排除的设备 IP 的逗号分隔列表



 a| 
包括设备
 a| 
要包括在轮询中的设备 IP 的逗号分隔列表



 a| 
检查设备类型
 a| 
选择此项可仅接受那些明确将自己公布为 Cisco 设备的设备



 a| 
主别名类型
 a| 
提供第一个首选项来解析别名。从以下选项中进行选择：

* *设备别名*
+
这是端口WWN (pWWN)的用户友好名称、可根据需要在所有配置命令中使用。Cisco MDS 9000 系列中的所有交换机都支持分布式设备别名服务（设备别名）。

* * 无 *
+
不报告任何别名

* *端口问题描述 *
+
一个问题描述 、用于帮助在端口列表中标识端口

* *分区别名(全部)*
+
端口的一个用户友好名称、仅可用于分区配置

* *分区别名(仅活动)*
+
端口的用户友好名称、仅可用于活动配置。这是默认值。





 a| 
二级别名类型
 a| 
请提供第二个首选项来解析别名



 a| 
三级别名类型
 a| 
提供第三个首选项来解析别名



 a| 
启用 SANTap 代理模式支持
 a| 
选择 Cisco 交换机是否在代理模式下使用 SANTap 。如果您使用的是 EMC RecoverPoint ，则可能是 SANTap 。



 a| 
性能轮询间隔（秒）
 a| 
性能轮询之间的时间间隔（默认值为 300 秒）

|===