---
permalink: config-admin/configuring-sso.html 
sidebar: sidebar 
keywords:  
summary: '单点登录(SSO)允许组织中的用户使用OnCommand Insight 、而无需特殊帐户。' 
---
= 配置单点登录(SSO)
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
单点登录(Single Sign-On、SSO)允许组织中的用户使用OnCommand Insight 、而无需特殊帐户。

管理员可以为企业域中的用户配置OnCommand Insight 服务器以实现*单点登录*(SSO)访问。在配置了SSO的情况下、具有域电子邮件地址的任何用户都可以使用其公司凭据登录到Insight。OnCommand Insight 支持用于SSO的OpenID连接(OIDC)协议。

[NOTE]
====
SSO仅适用于Insight Server基于Web的UI。SSO不适用于数据仓库、报告或Java客户端UI组件。

OnCommand洞察力仅支持对*Azure Active Directory*使用SSO。

====


== 配置SSO的步骤

* 导航到菜单：Admin[设置>用户]
* 输入SSO配置URL以自动填充配置字段(也称为"OpenID-configuration")。这是一个URI、用于提供描述身份提供程序配置的JSON。
* 或者、也可以手动输入以下身份提供程序资源的SSO配置URL。有关这些资源的详细信息、请参见此页面底部的相关信息部分。
+
** *授权端点*：一种身份提供程序资源、用于提示用户输入凭据。成功后、身份会向OnCommand Insight 发出授权授予、允许其代表用户执行操作。
** *。jwk set URI*：提供用于对JWT令牌签名的公共密钥。这样、客户端就可以验证JWT令牌是否实际由身份提供程序而不是第三方发出。
** *令牌端点*：身份提供程序资源、客户端在此资源中对JWT令牌进行授权授予交易。客户端还必须提供客户端ID和客户端密钥(请参见下文)。Insight使用的JWT令牌是"identity token"、表示用户的用户名和角色。
** *结束会话端点*：由身份提供程序提供、客户端(OCI)会将浏览器重定向到该身份提供程序、而身份提供程序会使用户与身份提供程序的会话失效。这意味着、在下次登录时、用户必须输入凭据。


* *客户端ID*：唯一标识客户端(OCI)、并将其与身份提供程序已知的其他客户端区分开。身份提供程序会在为其创建应用程序时生成客户端ID、并且客户端必须知道客户端ID、因为它会在令牌请求中显示此ID。
* *客户端机密*：只有身份提供程序和客户端知道的随机字符串、用于向身份提供程序对客户端进行身份验证、从而证明客户端是其声称的应用程序、而不是恶意第三方。在令牌请求中、客户端密钥与客户端ID一起传递给身份提供程序。客户端密钥由身份提供程序生成。使用Azure Active Directory时、允许使用多个客户端密钥。
* * JWT Claim for username*：标识JWT令牌中用于标识用户用户用户名的声明。声明是指JWT令牌的JSON有效负载中的密钥值对。配置的"JW Claim for username"是密钥的名称、对于每个身份令牌、该值是要进行身份验证的用户的用户名。密钥名称可能因身份提供程序而异。对于Azure Active Directory、声明名称通常为"preferred_username"。
* * JWT Claim for roles*：与上述内容类似、只是此声明的值是OCI角色列表、即"guest"、"user"、"admin"。对于Azure Active Directory、此密钥名为"角色"。




== 管理SSL证书

您必须导入身份提供程序的SSL证书链的根证书。为此、请下载与令牌端点的主机名关联的根证书。(适用于Azure Active Directory的login.microsoftonline.com)并将其保存到文件中。然后、单击"`Certificates`"按钮、并使用"`Manual`"选项卡选择文件并提供一个别名、例如"`sso-root`"以导入该文件。`

如果已启用SSO、并且您导入了新证书、则必须重新启动SANscreen 服务。



== 在操作系统中启用SSO

要在当前系统上启用SSO并通过升级保留soAuth系统属性、必须执行以下操作。

要在Windows上启用SSO、请导航到注册表中的_HKEY_LOCAL_MACHINE \SOFTWARE\NetApp\SANscreen_。将soAuth的值从false更改为true。此值在升级期间读取、用于为升级后的系统设置soAuth系统属性。它对当前实例没有影响；您还必须在_HKEY_LOCAL_MACHINE \SOFTWARE\Wow6432Node\Apache Software Foundation\Procrun 2.0\SANscreen Server\Parameters\Java Options_中更新ssoAuth。

要在Linux上启用SSO、请导航到_/opt/netapp/oci/conf/并打开文件_wildfly.properties_。将_sso_AUTH_ENenabled__的值从false更改为true。

启用SSO后、重新启动SANscreen 服务。



== 排除SSO问题

如果您收到"未授权"错误、请查看server.log以了解详细信息。如果Insight报告授权失败、但身份提供程序已正确对用户进行身份验证、您可能会看到此错误。

如果用户无法使用SSO登录、请以具有管理员权限的非SSO用户身份登录并更正SSO配置。为此、您可以在<Your Insight URL> 浏览器窗口中输入_logiserver/login_html##__.

* 相关信息 *

https://ldapwiki.com/wiki/Openid-configuration[]

https://ldapwiki.com/wiki/Authorization_endpoint[]

https://ldapwiki.com/wiki/JWK%20Set[]

https://ldapwiki.com/wiki/Token_endpoint[]

https://ldapwiki.com/wiki/End_session_endpoint[]

https://ldapwiki.com/wiki/Client_id[]

https://ldapwiki.com/wiki/Client%20Secret[]

https://ldapwiki.com/wiki/Identity%20Token[]
