---
permalink: config-admin/defining-applications.html 
sidebar: sidebar 
keywords:  
summary: 如果要跟踪与环境中运行的特定应用程序关联的数据、则需要定义这些应用程序。 
---
= 定义应用程序
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果要跟踪与环境中运行的特定应用程序关联的数据、则需要定义这些应用程序。



== 开始之前

如果要将应用程序与业务实体关联、必须已创建业务实体。



== 关于此任务

您可以将应用程序与以下资产相关联：主机，虚拟机，卷，内部卷， qtree ， 共享和虚拟机管理程序。



== 步骤

. 登录到OnCommand Insight Web UI。
. 单击*管理*并选择*应用程序*。
+
定义应用程序后、"应用程序"页面将显示应用程序的名称、优先级以及与应用程序关联的业务实体(如果适用)。

+
[NOTE]
====
如果安装了异常检测引擎、则应用程序信息板页面还会显示应用程序的异常分数。有关安装和配置异常检测引擎的详细信息、请参见_RAID OnCommand Insight 配置和管理指南_。

====
. 单击 * 添加 * 。
+
此时将显示添加应用程序对话框。

. 在*名称*框中输入应用程序的唯一名称。
. 单击*优先级*、然后为环境中的应用程序选择优先级(关键、高、中或低)。
. 如果您计划将此应用程序与业务实体结合使用、请单击*业务实体*并从列表中选择实体。
. *可选*：如果不使用卷共享、请单击以清除*验证卷共享*框。
+
这需要Assure许可证。如果要确保每个主机都可以访问集群中的相同卷、请设置此选项。例如、高可用性集群中的主机通常需要屏蔽到相同的卷才能进行故障转移；但是、不相关应用程序中的主机通常不需要访问相同的物理卷。此外、出于安全原因、监管策略可能要求您明确禁止不相关的应用程序访问相同的物理卷。

. 单击 * 保存 * 。
+
应用程序将显示在"Applications"页面中。如果单击应用程序的名称、Insight将显示应用程序的资产页面。





== 完成后

定义应用程序后、您可以转到主机、虚拟机、卷、内部卷或虚拟机管理程序的资产页面、以便将应用程序分配给资产。
