---
permalink: config-admin/device-resolution.html 
sidebar: sidebar 
keywords:  
summary: 您需要发现要使用OnCommand Insight 监控的所有设备。要准确跟踪环境中的性能和清单、需要进行发现。通常、环境中的大多数设备都是通过自动设备解析来发现的。 
---
= 设备解析
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您需要发现要使用OnCommand Insight 监控的所有设备。要准确跟踪环境中的性能和清单、需要进行发现。通常、环境中的大多数设备都是通过自动设备解析来发现的。

[NOTE]
====
如果您正在执行升级、并且要升级的系统中存在非活动的自动解析规则、则这些规则将在升级期间被删除。要保留非活动的自动解析规则、请在执行升级之前激活规则(选中复选框)。

====
安装和配置数据源后、系统将确定环境中的设备、包括交换机、存储阵列以及虚拟机管理程序和VM的虚拟基础架构。但是，这通常并不能识别您环境中的 100% 设备。

配置数据源类型的设备后、最佳实践是利用设备解析规则来帮助确定环境中其余未知设备。设备解析有助于将未知设备解析为以下设备类型：

* 物理主机
* 存储阵列
* 磁带
* 交换机


在设备解析后仍保留为"`unknown`"的设备被视为通用设备、您也可以在查询和信息板中显示这些设备。

然后，创建的规则将自动识别添加到环境中的具有类似属性的新设备。在某些情况下、设备解析还允许在Insight中绕过未发现设备的设备解析规则进行手动标识。

设备标识不完整可能会导致以下问题：

* 路径不完整
* 未标识的多路径连接
* 无法对应用程序进行分组
* 拓扑视图不准确
* 数据仓库和报告中的数据不准确


设备解析功能(*管理*>*设备解析*)包括以下选项卡、每个选项卡在设备解析规划和查看结果中都起着作用：

* "`FC identify`"包含未通过自动设备解析解决的光纤通道设备的WWN和端口信息列表。此选项卡还会标识已标识的设备的百分比。
* "`IP identify`"包含访问未通过自动设备解析进行标识的CIFS共享和NFS共享的设备列表。此选项卡还会标识已标识的设备的百分比。
* "`自动解析规则`"包含执行光纤通道设备解析时运行的规则列表。这些规则是您为解析未标识的光纤通道设备而创建的。
* "`首选项`"提供了一些配置选项、您可以使用这些选项为您的环境自定义设备解析。

