---
permalink: config-admin/emc-isilon-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: Isilon SSH数据源从EMC Isilon横向扩展NAS存储收集清单和性能。 
---
= EMC Isilon数据源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Isilon SSH数据源从EMC Isilon横向扩展NAS存储收集清单和性能。



== 术语

OnCommand Insight 从EMC Isilon数据源采集以下清单信息。对于Insight获取的每种资产类型、均显示了此资产最常用的术语。查看此数据源或对其进行故障排除时，请记住以下术语：

|===


| 供应商 / 型号术语 | Insight术语 


 a| 
驱动器
 a| 
Disk



 a| 
集群
 a| 
存储



 a| 
Node
 a| 
存储节点



 a| 
文件系统
 a| 
内部卷

|===
[NOTE]
====
这些只是常见的术语映射、可能并不代表此数据源的所有情形。

====


== 要求

* Isilon 存储的管理员权限
* 已使用验证访问 `telnet` 连接到端口22




== Configuration

|===


| 字段 | Description 


 a| 
IP 地址
 a| 
Isilon 集群的 IP 地址或完全限定域名



 a| 
用户名
 a| 
Isilon集群的用户名



 a| 
Password
 a| 
Isilon集群的密码

|===


== 高级配置

|===


| 字段 | Description 


 a| 
清单轮询间隔（分钟）
 a| 
两次清单轮询的间隔(默认为20分钟)



 a| 
性能轮询间隔（秒）
 a| 
性能轮询之间的时间间隔（默认值为 300 秒）



 a| 
SSH进程等待超时
 a| 
SSH进程超时(默认值为60秒)



 a| 
SSH 端口
 a| 
SSH 服务端口

|===


== 正在运行CLI命令

从OnCommand Insight 7.3.11和Service Pack 9开始、EMC Isilon数据源包含一项增强功能、可使Insight运行更多命令行界面命令。如果您在数据源中使用的是非root用户、则可能已配置一个"sudoers"文件、以使该用户帐户能够通过SSH运行特定的命令行界面命令。

为了让Insight了解EMC的"访问区域"功能、Insight现在还将运行以下新的命令行界面命令：

* `sudo isi zone zones list --format json –verbose`
* `sudo isi zone zones list`


Insight会分析这些命令的输出并运行更多现有命令实例、以获取非默认访问区域中的qtree、配额和NAS共享/导出等对象的逻辑配置。现在、Insight会通过此增强功能为非默认访问区域报告这些对象。由于Insight通过运行现有命令(使用不同的选项)来获取数据、因此无需对sudoers文件进行更改、这些命令才能正常运行；只有在上述新命令推出后、才需要进行更改。

在升级到此Insight版本之前、请更新sudoers文件以允许您的Insight服务帐户运行这些命令。否则、Isilon数据源将失败。



== "文件系统"统计信息

从OnCommand Insight 7.3.12开始、EMC Isilon数据收集器引入了EMC Isilon节点对象的"文件系统"统计信息。OnCommand Insight 报告的现有节点统计信息基于"磁盘"、即、对于存储节点的IOPS和吞吐量、此节点中的磁盘在聚合中执行了哪些操作？但是、对于读取缓存在内存中且/或正在使用数据压缩的工作负载、文件系统工作负载可能远远高于实际命中磁盘的工作负载-因此、压缩5：1的数据集可能具有5倍于存储节点读取吞吐量的"文件系统读取吞吐量"值、 后者用于测量磁盘的读取、当节点解压缩数据以满足客户端的读取请求时、磁盘将扩展5倍。
