---
permalink: config-admin/emc-vnxe-data-source.html 
sidebar: sidebar 
keywords:  
summary: EMC VNXe数据源为EMC VNXe和Unity统一存储阵列提供清单支持。 
---
= EMC VNXe数据源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
EMC VNXe数据源为EMC VNXe和Unity统一存储阵列提供清单支持。

此数据源基于CLI、需要在VNXe数据源所在的采集单元上安装Unisphere for VNXe CLI (uemcli.exe)。uemcli.exe使用HTTPS作为传输协议、因此采集单元必须能够启动与VNXe/Unity阵列的HTTPS连接。您必须至少具有一个只读用户以供数据源使用。



== 术语

OnCommand Insight 从EMC VNXe数据源采集以下清单信息。对于Insight获取的每种资产类型、均显示了此资产最常用的术语。查看此数据源或对其进行故障排除时，请记住以下术语：

|===


| 供应商 / 型号术语 | Insight术语 


 a| 
Disk
 a| 
Disk



 a| 
存储阵列
 a| 
存储



 a| 
处理器
 a| 
存储节点



 a| 
存储池
 a| 
存储池



 a| 
常规 iSCSI 块信息， VMware VMFS
 a| 
Volume



 a| 
共享文件夹
 a| 
内部卷



 a| 
CIFS共享、NFS共享、VMware NFS数据存储库中的共享
 a| 
共享



 a| 
复制远程系统
 a| 
同步



 a| 
iSCSI 节点
 a| 
iSCSI 目标节点



 a| 
iSCSI 启动程序
 a| 
iSCSI 目标启动程序

|===
[NOTE]
====
这些只是常见的术语映射、可能并不代表此数据源的所有情形。

====


== 要求

以下是配置和使用此数据源的要求：

* VNXe 数据收集器基于 CLI ；您必须将适用于 VNXe CLI 的 Unisphere （ uemcli.exe ）安装到 VNXe 数据收集器所在的采集单元上。
* uemcli.exe 使用 HTTPS 作为传输协议，因此采集单元需要能够启动与 VNXe 的 HTTPS 连接。
* 您必须至少具有一个只读用户以供数据源使用。
* 管理解决方案启用程序服务器的 IP 地址。
* 端口 443 上的 HTTPS 为必填项
* EMC VNXe数据收集器为清单提供NAS和iSCSI支持；将发现光纤通道卷、但Insight不会报告FC映射、屏蔽或存储端口。




== Configuration

|===


| 字段 | Description 


 a| 
VNXe 存储
 a| 
VNXe 设备的 IP 地址或完全限定域名



 a| 
用户名
 a| 
VNXe 设备的用户名



 a| 
Password
 a| 
VNXe 设备的密码



 a| 
uemcli可执行文件的完整路径
 a| 
的完整路径 `uemcli.exe` 可执行文件

|===


== 高级配置

|===


| 字段 | Description 


 a| 
清单轮询间隔（分钟）
 a| 
两次清单轮询的间隔（默认为 40 分钟）



 a| 
VNXe命令行界面端口
 a| 
用于 VNXe 命令行界面的端口



 a| 
清单外部进程超时(秒)
 a| 
外部进程超时(默认值为1800秒)

|===