---
permalink: config-admin/examining-network-performance.html 
sidebar: sidebar 
keywords:  
summary: 您可以检查存储环境的性能、确定未充分利用和过度利用的资源、并在风险转化为问题之前确定风险。 
---
= 检查网络性能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以检查存储环境的性能、确定未充分利用和过度利用的资源、并在风险转化为问题之前确定风险。

Insight可帮助您解决或防止通过收集的存储数据发现的性能和可用性问题。

您可以使用Insight执行以下性能管理任务：

* 监控整个环境的性能
* 确定影响其他设备性能的资源




== 端口的重要性

Insight服务器和数据仓库(DWH)服务器可能需要多个可用的TCP端口才能可靠地运行。其中某些端口仅用于绑定到本地主机适配器(127.0.0.1)的进程、但核心服务仍需要使用这些端口才能可靠地运行。所需的端口数是网络中使用的端口数的超集。



== Insight服务器端口

Insight服务器可以安装软件防火墙。需要打开的"孔"如下所述。

*入站HTTPS 443*-假设您的Insight WebUI运行在TCP 443上、则必须将其公开、以便允许以下任何及所有使用者：

* WebUI的Insight用户
* 希望连接到Insight服务器的远程采集单元
* 具有与此Insight服务器连接的OCI DWH服务器。
* 与Insight REST API的任何编程交互


对于希望实施Insight服务器主机级防火墙的任何人、我们的一般建议是允许对所有企业网络IP块进行HTTPS访问。

*入站MySQL (TCP 3306)*。此端口只需要公开到具有连接器的任何Insight DWH服务器

虽然Insight拥有数十个数据收集器、但它们都是基于轮询的—Insight将对其采集单元(AUS)进行发生原因 、以便启动与各种设备的出站通信。只要基于主机的防火墙处于"状态"状态、允许通过防火墙返回流量、Insight服务器上基于主机的防火墙就不应影响数据采集。



== 数据仓库端口

对于Insight DWH服务器：

*入站HTTPS 443*-假设您的Insight WebUI运行在TCP 443上、则必须公开此内容以允许以下使用者：

* DWH管理门户的Insight管理用户


*入站HTTPS (TCP 9300)*—这是Cognos报告接口。如果用户要与Cognos报告界面进行交互、则必须远程公开此信息。

我们可以想象、可能不需要公开DWH的环境—报告作者可能只是与DWH服务器建立RDP连接、然后在那里创建和计划报告、同时计划通过SMTP交付或写入远程文件系统的所有报告。

*入站MySQL (TCP 3306)*。只有当您的组织与DWH数据具有任何基于MySQL的集成时、才需要公开此端口—您是否从各种DWH数据集市中提取数据以输入到其他应用程序中、例如CMDB、成本分摊系统等
