---
permalink: config-admin/ibm-svc-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: IBM SVC数据源使用SSH收集清单和性能数据、支持运行SVC操作系统的各种设备。支持的设备列表包括 SVC ， v7000 ， V5000 和 V3700 等型号。有关支持的型号和固件版本、请参见Insight数据源支持列表。 
---
= IBM SVC数据源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM SVC数据源使用SSH收集清单和性能数据、支持运行SVC操作系统的各种设备。支持的设备列表包括 SVC ， v7000 ， V5000 和 V3700 等型号。有关支持的型号和固件版本、请参见Insight数据源支持列表。



== 术语

OnCommand Insight 从IBM SVC数据源采集以下清单信息。对于Insight获取的每种资产类型、均显示了此资产最常用的术语。查看此数据源或对其进行故障排除时，请记住以下术语：

|===


| 供应商 / 型号术语 | Insight术语 


 a| 
驱动器
 a| 
Disk



 a| 
集群
 a| 
存储



 a| 
Node
 a| 
存储节点



 a| 
Mdisk 组
 a| 
存储池



 a| 
vDisk
 a| 
Volume



 a| 
Mdisk
 a| 
后端 LUN

|===
[NOTE]
====
这些只是常见的术语映射、可能并不代表此数据源的所有情形。

====


== 清单要求

* 每个 SVC 集群的 IP 地址
* 端口 22 可用
* 您可以通过Insight生成的公共和专用密钥对、也可以重复使用SVC上已在使用的密钥对
+
如果要重复使用现有密钥对、则必须将其从Putty格式转换为OpenSSH格式。

* 公共密钥安装在SVC集群上
* 需要在数据源中标识私钥
* 访问验证：打开 `ssh` 使用私钥与SVC集群进行会话


[NOTE]
====
无需安装第三方软件。

====


== 性能要求

* SVC 控制台，任何 SVC 集群都必须使用此控制台， SVC 发现基础包也需要此控制台。
* 只有将性能数据文件从集群节点复制到配置节点时才需要管理访问级别。
+
[NOTE]
====
由于SVC基础发现包不需要此访问级别、因此SVC基础用户可能无法成功工作。

====
* 需要端口22
* 必须为此用户生成私有和公共SSH密钥、并存储私钥、以便可从采集单元访问。如果SVC基础用户具有适当的权限、则相同的用户和密钥将正常工作。同一SSH密钥可用于清单和性能数据。
* 通过SSH连接到SVC集群并运行以下命令来启用数据收集： `svctask startstats -interval 1`
+
[NOTE]
====
或者、也可以使用SVC管理用户界面启用数据收集。

====




== 说明了父级序列号

传统上、Insight可以报告存储阵列序列号或单个存储节点序列号。但是、某些存储阵列架构并不完全符合此要求。一个SVC集群可以由1-4个设备组成、每个设备都有2个节点。如果设备本身具有序列号、则该序列号既不是集群的序列号、也不是节点的序列号。

如果各个节点位于仅属于较大集群一部分的中间设备/机箱中、则存储节点对象上的"父序列号"属性会针对IBM SVC阵列正确填充。



== Configuration

|===


| * 字段 * | * 问题描述 * 


 a| 
集群IP
 a| 
SVC存储的完全限定域名的IP地址



 a| 
选择 " 密码 " 或 "OpenSSH 密钥文件 " 以指定凭据类型
 a| 
用于通过SSH连接到设备的凭据类型



 a| 
清单用户名
 a| 
SVC 命令行界面的用户名



 a| 
清单密码
 a| 
SVC 命令行界面的密码



 a| 
清单专用密钥的完整路径
 a| 
清单专用密钥文件的完整路径



 a| 
性能用户名
 a| 
用于收集性能的SVC命令行界面的用户名



 a| 
性能密码
 a| 
用于收集性能的SVC命令行界面的密码



 a| 
性能专用密钥的完整路径
 a| 
性能私钥文件的完整路径

|===


== 高级配置

|===


| * 字段 * | * 问题描述 * 


 a| 
清单轮询间隔（分钟）
 a| 
两次清单轮询的间隔（默认为 40 分钟）



 a| 
排除设备
 a| 
要从清单收集中排除的设备ID的逗号分隔列表



 a| 
SSH进程等待超时(秒)
 a| 
SSH进程超时(默认为200秒)



 a| 
性能轮询间隔（秒）
 a| 
性能轮询之间的时间间隔（默认值为 300 秒）



 a| 
性能排除设备
 a| 
要从性能收集中排除的设备ID的逗号分隔列表



 a| 
性能SSH进程等待超时(秒)
 a| 
SSH进程超时(默认为200秒)



 a| 
清理转储的统计信息文件
 a| 
选择此选项可清除转储的统计信息文件

|===