---
permalink: config-admin/ibm-powervm-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'IBM PowerVM\(SSH\)数据源收集有关在由硬件管理控制台管理的IBM POWER硬件实例上运行的虚拟分区的信息。对于配置、此数据源需要用户名才能通过SSH登录到HMC、并需要对HMC配置具有查看级别权限。' 
---
= IBM PowerVM数据源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM PowerVM (SSH)数据源收集有关在由硬件管理控制台(HMC)管理的IBM POWER硬件实例上运行的虚拟分区的信息。对于配置、此数据源需要用户名才能通过SSH登录到HMC、并需要对HMC配置具有查看级别权限。



== 术语

OnCommand Insight 从IBM PowerVM数据源采集以下清单信息。对于Insight获取的每种资产类型、均显示了此资产最常用的术语。查看此数据源或对其进行故障排除时，请记住以下术语：

|===


| 供应商 / 型号术语 | Insight术语 


 a| 
hdisk
 a| 
虚拟磁盘



 a| 
受管系统
 a| 
主机



 a| 
LPAR ， VIO 服务器
 a| 
虚拟机



 a| 
卷组
 a| 
数据存储



 a| 
物理卷
 a| 
LUN

|===
[NOTE]
====
这些只是常见的术语映射、可能并不代表此数据源的所有情形。

====


== 要求

* 硬件管理控制台（ HMC ）的 IP 地址
* 通过SSH访问HMC的用户名和密码
* 端口要求 SSH-22
* 查看所有管理系统和逻辑分区安全域的权限
+
用户还必须对 HMC 配置拥有查看权限，并能够为 HMC 控制台安全分组收集 VPD 信息。在逻辑分区安全分组下，还必须允许用户访问虚拟 IO 服务器命令。最好从操作员角色开始，然后删除所有角色。HMC 上的只读用户无权在 AIX 主机上运行代理命令。

* IBM 最佳实践是，让两个或更多 HMCS 监控设备。请注意，这可能是发生原因 OnCommand Insight 报告重复的设备，因此强烈建议将冗余设备添加到此数据收集器的高级配置中的 " 排除设备 " 列表中。




== Configuration

|===


| * 字段 * | * 问题描述 * 


 a| 
硬件管理控制台(HMC)地址
 a| 
PowerVM 硬件管理控制台的 IP 地址或完全限定域名



 a| 
HMC 用户
 a| 
硬件管理控制台的用户名



 a| 
Password
 a| 
硬件管理控制台使用的密码

|===


== 高级配置

|===


| * 字段 * | * 问题描述 * 


 a| 
清单轮询间隔（分钟）
 a| 
两次清单轮询的间隔(默认为20分钟)



 a| 
SSH 端口
 a| 
用于通过 SSH 连接到 PowerVM 的端口



 a| 
SSH进程等待超时(秒)
 a| 
SSH进程超时(默认值为600秒)



 a| 
重试次数
 a| 
清单重试尝试次数



 a| 
排除设备
 a| 
要排除的设备 ID 或显示名称的逗号分隔列表

|===