---
permalink: config-admin/importing-and-exporting-user-data.html 
sidebar: sidebar 
keywords:  
summary: 通过导入和导出功能、您可以将标注、标注规则、查询、性能策略和自定义信息板导出到一个文件。然后、可以将此文件导入到不同的OnCommand Insight 服务器中。 
---
= 导入和导出用户数据
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过导入和导出功能、您可以将标注、标注规则、查询、性能策略和自定义信息板导出到一个文件。然后、可以将此文件导入到不同的OnCommand Insight 服务器中。

只有运行相同版本OnCommand Insight 的服务器之间才支持导出和导入功能。

要导出或导入用户数据、请单击*管理*并选择*设置*、然后选择*导入/导出用户数据*选项卡。

在导入操作期间，系统会根据要导入的对象和对象类型添加，合并或替换数据。

* 标注类型
+
** 如果目标系统中不存在同名标注、则添加标注。
** 如果标注类型为列表，并且目标系统中存在同名标注，则合并标注。
** 如果标注类型不是列表，并且目标系统中存在同名标注，则替换标注。


+
[NOTE]
====
如果目标系统中存在同名但类型不同的标注、导入将失败。如果对象依赖于失败的标注，则这些对象可能显示不正确或不需要的信息。导入操作完成后，您必须检查所有标注依赖关系。

====
* 标注规则
+
** 如果目标系统中不存在同名标注规则、则添加标注规则。
** 如果目标系统中存在同名标注规则、则替换标注规则。


+
[NOTE]
====
标注规则取决于查询和标注。导入操作完成后、您必须检查所有标注规则的准确性。

====
* 策略
+
** 如果目标系统中不存在同名策略、则添加策略。
** 如果目标系统中存在同名策略、则替换策略。


+
[NOTE]
====
导入操作完成后、策略可能会无序。必须在导入后检查策略顺序。如果标注不正确、则依赖于标注的策略可能会失败。您必须在导入后检查所有标注依赖关系。

+

====
* 查询
+
** 如果目标系统中不存在同名查询、则添加查询。
** 如果目标系统中存在同名查询、则替换查询、即使查询的资源类型不同也是如此。


+
[NOTE]
====
如果查询的资源类型不同、则在导入后、使用该查询的任何信息板小工具可能会显示不需要的或不正确的结果。导入后、您必须检查所有基于查询的小工具的准确性。如果标注不正确、则依赖于标注的查询可能会失败。您必须在导入后检查所有标注依赖关系。

+

====
* 信息板
+
** 如果目标系统中不存在同名信息板、则添加信息板。
** 如果目标系统中存在同名信息板、则替换信息板、即使查询的资源类型不同也是如此。


+
[NOTE]
====
导入后、您必须检查信息板中所有基于查询的小工具的准确性。如果源服务器具有多个同名信息板、则所有信息板都将导出。但是、只会将第一个导入到目标服务器中。为了避免导入期间出现错误、您应确保信息板在导出之前具有唯一的名称。

+

====

