---
permalink: config-admin/managing-security-on-an-rau.html 
sidebar: sidebar 
keywords: rekey 
summary: 使用securityadmin工具可以管理RAU上的安全选项。您可能需要备份或还原存储配置、更改加密密钥或更新采集单元的密码。 
---
= 管理RAU上的安全性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 `securityadmin` 使用工具可以管理RAU上的安全选项。您可能需要备份或还原存储配置、更改加密密钥或更新采集单元的密码。



== 关于此任务

您可以使用 `securityadmin` 用于管理安全性的工具：

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`


更新LAU安全配置的一种情形是、在服务器上更改了"采集"用户密码后、RAU会更新该用户的密码。所有RAU和LAU都使用与服务器"采集"用户相同的密码与服务器进行通信。

[NOTE]
====

====
"采集"用户仅存在于Insight服务器上。RAU或LAU在连接到服务器时以该用户身份登录。

使用以下步骤管理RAU上的安全选项：



== 步骤

. 远程登录到运行RAU的服务器
. 在交互模式下启动安全管理工具： `Windows - C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i``Linux - /bin/oci-securityadmin.sh -i`
+
系统请求登录凭据。

. 输入具有"`Admin`"凭据的帐户的用户名和密码。
+
系统将显示RAU的菜单。

+
** * 备份 *
+
为包含所有密码和密钥的存储创建一个备份zip文件、并将该文件放置在用户指定的位置或以下默认位置：

+
*** Windows - `C:\Program Files\SANscreen\backup\vault`
*** Linux - `/var/log/netapp/oci/backup/vault`


** * 还原 *
+
还原已创建的存储的zip备份。还原后、所有密码和密钥将还原为创建备份时的现有值。

+
[NOTE]
====
还原可用于同步多个服务器上的密码和密钥、例如：-更改一个服务器上的加密密钥-创建存储备份-将存储备份还原到第二个服务器

+

====
** *更改加密密钥*
+
更改用于对设备密码进行加密或解密的RAU加密密钥。

+
[NOTE]
====
更改加密密钥时、您应备份新的安全配置、以便在升级或安装后还原它。

====
** *更新密码*
+
更改"采集"用户帐户的密码。

+
[NOTE]
====
更改密码后、某些帐户需要同步。例如、如果您更改服务器上"采集"用户的密码、则需要更改LAU、RAU和DWH上"采集"用户的密码以使其匹配。此外、更改密码时、您应备份新的安全配置、以便在升级或安装后还原它。

====
** *重置为默认值*
+
将加密密钥和密码重置为默认值。默认值是在安装期间提供的值。

** * 退出 *
+
退出 `securityadmin` 工具。




