---
permalink: config-admin/managing-security-on-the-local-acquisition-unit.html 
sidebar: sidebar 
keywords:  
summary: '使用securityadmin工具可以管理本地采集用户\(LAU)上的安全选项。安全管理包括管理密钥和密码、保存和还原您创建的安全配置或将配置还原为默认设置。' 
---
= 管理本地采集单元上的安全性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 `securityadmin` 使用工具可以管理本地采集用户(LAU)上的安全选项。安全管理包括管理密钥和密码、保存和还原您创建的安全配置或将配置还原为默认设置。



== 开始之前

您必须拥有 `admin` 执行安全配置任务的权限。



== 关于此任务

您可以使用 `securityadmin` 用于管理安全性的工具：

* Windows - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`




== 步骤

. 远程登录到Insight服务器。
. 以交互模式(-I)启动安全管理工具。
+
系统请求登录凭据。

. 输入具有"`Admin`"凭据的帐户的用户名和密码。
. 选择*本地采集单元*以重新配置本地采集单元安全配置。
+
此时将显示以下选项：

+
** * 备份 *
+
为包含所有密码和密钥的存储创建一个备份zip文件、并将该文件放置在用户指定的位置或以下默认位置：

+
*** Windows - `C:\Program Files\SANscreen\backup\vault`
*** Linux - `/var/log/netapp/oci/backup/vault`


** * 还原 *
+
还原已创建的存储的zip备份。还原后、所有密码和密钥将还原为创建备份时的现有值。

+
[NOTE]
====
还原可用于同步多个服务器上的密码和密钥、例如：-更改LAU上的加密密钥-创建存储备份-将存储备份还原到每个RAU

+

====
** *更改加密密钥*
+
更改用于对设备密码进行加密或解密的AU加密密钥。

+
[NOTE]
====
更改加密密钥时、您应备份新的安全配置、以便在升级或安装后还原它。

====
** *更新密码*
+
更改"采集"用户帐户的密码。

+
[NOTE]
====
更改密码后、某些帐户需要同步。例如、如果您更改服务器上"采集"用户的密码、则需要更改LAU、RAU和DWH上"采集"用户的密码以使其匹配。此外、更改密码时、您应备份新的安全配置、以便在升级或安装后还原它。

====
** *重置为默认值*
+
将采集用户密码和采集用户加密密钥重置为默认值、默认值是在安装期间提供的值。

** * 退出 *
+
退出 `securityadmin` 工具。



. 选择要配置的选项、然后按照提示进行操作。

