---
permalink: config-admin/metric-definitions.html 
sidebar: sidebar 
keywords:  
summary: '资产页面的 "Expert View" 部分会根据为资产选择的时间段显示多个指标。每个指标都会显示在自己的性能图表中。您可以根据要查看的数据在图表中添加或删除指标和相关资产。' 
---
= 专家视图指标定义
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
资产页面的 "Expert View" 部分会根据为资产选择的时间段显示多个指标。每个指标都会显示在自己的性能图表中。您可以根据要查看的数据在图表中添加或删除指标和相关资产。

|===


| 衡量指标 | Description 


 a| 
BB 信用零 Rx ， Tx
 a| 
取样期间接收 / 传输缓冲区到缓冲区信用计数过渡到零的次数。此度量指标表示连接的端口由于缺少可提供的信用值而不得不停止传输的次数。



 a| 
BB 信用零持续时间 Tx
 a| 
采样间隔内传输 BB 信用值为零的时间（以毫秒为单位）。



 a| 
缓存命中率（总计，读取，写入） %
 a| 
导致缓存命中的请求百分比。对卷的命中次数与访问次数之比越高，性能越好。对于不收集缓存命中信息的存储阵列，此列为空。



 a| 
缓存利用率（总计） %
 a| 
导致缓存命中的缓存请求的总百分比



 a| 
类 3 丢弃
 a| 
光纤通道 3 类数据传输丢弃的计数。



 a| 
CPU 利用率（总计） %
 a| 
活动使用的 CPU 资源量，占总可用资源的百分比（对于所有虚拟 CPU ）。



 a| 
CRC 错误
 a| 
取样期间端口检测到的具有无效循环冗余检查（ CRC ）的帧数



 a| 
帧速率
 a| 
以每秒帧数（帧数 / 秒）为单位的传输帧速率



 a| 
帧大小平均值（ Rx ， Tx ）
 a| 
流量与帧大小的比率。通过此指标，您可以确定网络结构中是否存在任何开销帧。



 a| 
帧大小太长
 a| 
过长的光纤通道数据传输帧的数量。



 a| 
帧大小太短
 a| 
太短的光纤通道数据传输帧的数量。



 a| 
I/O 密度（总，读取，写入）
 a| 
IOPS 数除以卷，内部卷或存储元素的已用容量（从数据源的最新清单轮询中获取）。以每 TB 每秒 I/O 操作数为单位。



 a| 
IOPS （总计，读取，写入）
 a| 
单位时间内通过 I/O 通道或该通道一部分的读 / 写 I/O 服务请求数（以每秒 I/O 数为单位）



 a| 
IP 吞吐量（总吞吐量，读取吞吐量，写入吞吐量）
 a| 
Total ：以 MB/ 秒为单位传输和接收 IP 数据的聚合速率。Read：IP Throughput (Receive)：接收IP数据的平均速率、以MB/秒为单位。

Write：IP Throughput (Transmit)：以MB/秒为单位传输IP数据的平均速率。



 a| 
延迟（总计，读取，写入）
 a| 
延迟（ R&W ）：在固定时间内向虚拟机读取或写入数据的速率。此值以 MB/ 秒为单位。

Latency：数据存储中虚拟机的平均响应时间。

Top Latency：数据存储中虚拟机的最长响应时间。



 a| 
链路故障
 a| 
取样期间端口检测到的链路故障数量。



 a| 
链路重置 Rx ， Tx
 a| 
取样期间接收或传输链路重置的数量。此指标表示连接的端口对此端口发出的链路重置次数。



 a| 
内存利用率（总计） %
 a| 
主机使用的内存阈值。



 a| 
部分读 / 写（总计） %
 a| 
读 / 写操作跨越 RAID 5 ， RAID 1/0 或 RAID 0 LUN 中任何磁盘模块上的条带边界的总次数通常，条带跨越并不有益，因为每个条带跨越都需要额外的 I/O百分比较低表示条带元素大小效率较高，并表示卷（或 NetApp LUN ）对齐不正确。

对于 CLARiiON ，此值是条带跨越次数除以 IOPS 总数。



 a| 
端口错误
 a| 
报告取样期间 / 给定时间范围内的端口错误。



 a| 
信号丢失计数
 a| 
信号丢失错误的数量。如果发生信号丢失错误，则表示没有电气连接，并且存在物理问题。



 a| 
交换速率（总速率，速率，出速率）
 a| 
在取样期间，从磁盘到活动内存的内存换入，移出或同时从磁盘到活动内存的速率。此计数器用于计数适用场景虚拟机。



 a| 
同步丢失计数
 a| 
同步丢失错误的数量。如果发生同步丢失错误，则硬件无法识别流量或锁定到该流量上。所有设备可能使用的数据速率不同，或者光纤或物理连接的质量可能较差。端口必须在每次出现此类错误后重新同步，这会影响系统性能。以 KB/ 秒为单位



 a| 
吞吐量（总吞吐量，读取吞吐量，写入吞吐量）
 a| 
在响应 I/O 服务请求的固定时间内传输，接收或同时接收数据的速率（以 MB/ 秒为单位）。



 a| 
丢弃帧超时— Tx
 a| 
因超时而丢弃的传输帧数。



 a| 
流量速率（总计，读取，写入）
 a| 
取样期间传输，接收或同时接收的流量，以每秒兆字节为单位。



 a| 
流量利用率（总计，读取，写入）
 a| 
取样期间接收 / 传输 / 总流量与接收 / 发送 / 总容量之比。



 a| 
利用率（总计，读取，写入） %
 a| 
用于传输（ Tx ）和接收（ Rx ）的可用带宽百分比。



 a| 
写入待处理（总计）
 a| 
待处理的写入 I/O 服务请求数。

|===