---
permalink: config-admin/microsoft-azure-compute-data-source.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insights使用Azure计算数据收集器从Azure计算实例采集清单和性能数据。 
---
= Microsoft Azure计算数据源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insights使用Azure计算数据收集器从Azure计算实例采集清单和性能数据。



== 要求

要配置此数据收集器，您需要以下信息：

* 端口要求： 443 HTTPS
* Azure 管理 REST IP （ management.azure.com ）
* Azure服务主体应用程序(客户端) ID (用户帐户)
* Azure服务主体身份验证密钥(用户密码)


您需要为Insight发现设置Azure帐户。正确配置帐户并在Azure中注册应用程序后、您将拥有在Insight中发现Azure实例所需的凭据。以下链接介绍了如何为发现设置帐户：https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal



== Configuration

根据下表在数据源字段中输入数据：

|===


| 字段 | Description 


 a| 
Azure 服务主体应用程序（客户端） ID （需要读取器角色）
 a| 
登录到 Azure 的 ID 。需要读取器角色访问。



 a| 
Azure 租户 ID
 a| 
Microsoft 租户 ID



 a| 
Azure 服务主体身份验证密钥
 a| 
登录身份验证密钥



 a| 
我了解 Microsoft 为 API 请求向我收费
 a| 
选中此复选框可验证您是否了解 Microsoft 会为 Insight 轮询发出的 API 请求向您收费。

|===


== 高级配置

根据下表在数据源字段中输入数据：

|===


| 字段 | Description 


 a| 
清单轮询间隔（分钟）
 a| 
默认值为 60 。



 a| 
选择 " 排除 " 或 " 包括 " 以应用于按标记筛选 VM
 a| 
指定在收集数据时是包含还是排除虚拟机的按标记。如果选择"`include`"、则标记密钥字段不能为空。



 a| 
标记要筛选 VM 的密钥和值
 a| 
单击 * + Filter Tag * ，通过筛选与 VM 上的密钥和标记值匹配的密钥和值来选择要包含 / 排除的 VM （以及关联磁盘）。标记密钥为必填项，标记值为可选项。如果标记值为空，则只要虚拟机与标记密钥匹配，就会对其进行筛选。



 a| 
性能轮询间隔(秒)|
 a| 
默认值为 300 。

|===