---
permalink: config-admin/monitoring-oncommand-insight-system-health.html 
sidebar: sidebar 
keywords:  
summary: 您应通过查看运行状况页面定期检查Insight系统组件的当前状态、该页面会显示每个组件的状态、并在存在问题描述 时向您发出警报。 
---
= 监控OnCommand Insight 系统运行状况
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您应通过查看运行状况页面定期检查Insight系统组件的当前状态、该页面会显示每个组件的状态、并在存在问题描述 时向您发出警报。



== 步骤

. 登录到InsightWeb UI。
. 单击*管理*并选择*运行状况*。
+
此时将显示"运行状况"页面。

. 查看组件的当前状态摘要、尤其要注意前面带有红色圆圈的*详细信息*列中的任何注意状态、该圆圈表示需要立即引起关注的问题描述。
+
"运行状况"页面根据您的系统配置显示以下任意或所有Insight组件的信息：

+
|===


| 组件 | 测试 | 详细信息 | 显示 


 a| 
采集
 a| 
清单数据处理
 a| 
本地采集单元的状态
 a| 
如果并发轮询数据源的数量小于执行池最大值的75%(默认最大值为30)、则为"`OK`"。如果使用率大于75%、则为"`Acquisition is busy`"、建议增加轮询间隔或添加更多远程采集单元。



 a| 
DWH
 a| 
备份
 a| 
数据仓库计划备份的状态
 a| 
如果启用了DWH计划备份、则显示"`OK`"和上次成功的DWH备份时间。否则、将显示有关发现的任何错误的信息。



 a| 
DWH
 a| 
ETL
 a| 
数据仓库ETL的状态
 a| 
"`正常`"和上次成功的DWH构建时间(如果没有错误)。否则、将显示有关发现的任何错误的信息。



 a| 
服务器
 a| 
ASUP
 a| 
ASUP的状态
 a| 
"`ASUP Enabled`"和上次成功的自动通报时间(如果可用)。如果已启用自动通报、但遇到问题、则显示"`ASUP Failed`"。

如果备份目录无效、则+"备份位置无效"。

+显示上次成功的自动通报时间以及上次失败尝试的时间(如果可用)。

如果已禁用自动通报、则+"`ASUP Disabled`"。



 a| 
服务器
 a| 
自动解析
 a| 
自动设备解析的状态
 a| 
如果没有错误、则显示"`OK`"。如果标识错误阻止解决进度、则显示"`Auto resolution is blocked`"。

+"`低成功率`"、前提是可以识别不到75%的通用设备。



 a| 
服务器
 a| 
Elasticsearch
 a| 
弹性搜索数据存储的状态
 a| 
如果没有错误、则显示"`OK`"。如果无法连接到弹性搜索服务、则显示"服务不可用`s`"。

如果检测到多个节点、则+"检测到集群模式"。

如果已用堆空间超过85%、则+"高内存利用率"。

+"状态：红色"表示弹性搜索报告的错误。显示有关此错误的信息、并建议联系客户支持。



 a| 
服务器
 a| 
CPU
 a| 
Insight CPU使用情况
 a| 
如果CPU负载小于65%、则为"`正常`"。"`sCPU负载较高。降低CPU负载。`" CPU负载大于65%。



 a| 
服务器
 a| 
磁盘空间
 a| 
磁盘空间的状态
 a| 
可用磁盘空间、Insight正在使用的磁盘空间以及建议为Insight预留的磁盘空间。如果磁盘利用率超过80%、则为"`磁盘空间不足`"。



 a| 
服务器
 a| 
EventBus
 a| 
EventBus的状态
 a| 
如果EventBus队列为空、则为"`EventBus is empty`"、否则将显示EventBus队列的状态。



 a| 
服务器
 a| 
清单数据处理
 a| 
Insight服务器清单数据处理功能的状态
 a| 
如果Insight服务器不繁忙、则显示"`OK`"。如果服务器在过去一小时中至少有75%的时间处于繁忙状态、则显示"`sserver is busy`"。建议不要添加更多数据源、并建议将环境拆分为多个服务器。



 a| 
服务器
 a| 
MySQL
 a| 
MySQL数据库的状态
 a| 
如果未检测到问题、则显示"`OK`"。"`数据库存在性能问题。如果较慢的查询数超过5%、则某些查询运行时间过长`。

+"`数据库日志文件在过去一小时内的增长超过了<size>。如果错误日志增长到20 KB以上、请检查MySQL日志文件`。



 a| 
服务器
 a| 
性能归档
 a| 
性能归档的状态
 a| 
"`性能归档已启用`"或"`性能归档未启用`"。



 a| 
服务器
 a| 
物理内存
 a| 
物理内存的状态
 a| 
如果内存使用率低于85%、则为"`正常`"。"`m使用率很高。如果内存使用率超过85%、请减少整体内存占用空间以确保系统稳定性`。



 a| 
服务器
 a| 
服务包
 a| 
Service Pack可用性
 a| 
显示是否有可用于Insight的Service Pack。如果有可用的Service Pack、则显示相关说明。



 a| 
服务器
 a| 
使用情况信息
 a| 
发送使用情况信息的状态
 a| 
显示是启用还是禁用向NetApp发送使用情况信息。如果已禁用、建议启用。显示上次尝试发送的时间或上次成功发送的时间。

+显示有关遇到的任何问题的信息。



 a| 
服务器
 a| 
违规
 a| 
未处理违规的状态
 a| 
如果未处理的违规数量小于违规限制的75%、则为"`OK`"。如果未解决的违规数超过违规限制的75%、则`m允许的最大未解决违规数为<number>`。建议查看性能策略配置。

如果未处理的违规数量达到违规限制、则+"`Violation manager is blocked`"。

+请注意、违规管理器无法创建新的违规、因此建议查看性能策略配置。



 a| 
服务器
 a| 
每周备份
 a| 
每周备份的状态
 a| 
如果启用了每周备份、则会显示"`正常`"、否则会显示"`未启用每周备份`"。

|===

