---
permalink: config-admin/netapp-host-and-vm-filesystems-data-source.html 
sidebar: sidebar 
keywords:  
summary: '您可以使用NetApp主机和VM文件系统数据源检索所有Microsoft Windows主机和VM \(虚拟机\)文件系统以及所有受支持的Linux VM \(仅虚拟映射的VM)的文件系统详细信息和存储资源映射 位于Insight服务器中、并使用已配置的计算资源组(CRG\)进行标注。' 
---
= NetApp主机和VM文件系统数据源
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用NetApp主机和VM文件系统数据源检索所有Microsoft Windows主机和VM (虚拟机)文件系统以及所有受支持的Linux VM (仅虚拟映射的VM)的文件系统详细信息和存储资源映射 位于Insight服务器中、并使用已配置的计算资源组(Compute Resource Group、CRG)进行标注。



== 一般要求

* 此功能必须单独购买。
+
您可以联系Insight代表以获得帮助。

* 您应查看Insight支持列表以验证您的主机或虚拟机操作系统是否受支持。
+
要验证是否已创建从文件系统到存储资源的链接、请检查相关存储或虚拟化供应商类型和版本是否报告所需的卷或虚拟磁盘标识数据。





== Microsoft Windows要求

* 此数据源使用Window Management Instrumentation (WMI)数据结构来检索数据。
+
此服务必须正常运行且可远程访问。特别是、端口135必须可访问、如果位于防火墙后面、则必须打开。

* Windows域用户必须具有访问WMI结构的相应权限。
* 需要管理员权限。
* 为Windows 2003及更早版本分配了1024-65535的动态TCP端口
* 端口49152--65535、适用于Windows 2008


[NOTE]
====
通常、在尝试在Insight、AU和此数据源之间使用防火墙时、您应咨询Microsoft团队、确定他们认为需要的端口。

====


== Linux要求

* 此数据源使用安全Shell (SSH)连接在Linux VM上执行命令。
+
SSH服务必须正常运行且可远程访问。特别是、端口22必须可访问、如果位于防火墙后面、则必须打开。

* SSH用户必须具有sudo权限才能在Linux VM上执行只读命令。
+
您必须使用相同的密码登录到SSH并对任何sudo密码质询进行问题解答。





== 使用建议

* 您应使用相同的计算资源组标注为一组具有通用操作系统凭据的主机和虚拟机添加标注。
+
每个组都有一个此数据源的实例、用于从这些主机和虚拟机发现文件系统详细信息。

* 如果此数据源的某个实例的成功率较低(例如、OnCommand Insight 仅发现组中1000个主机和虚拟机中50个的文件系统详细信息)、 您应将成功发现的主机和虚拟机移动到单独的计算资源组中。




== Configuration

|===


| 字段 | Description 


 a| 
用户名
 a| 
操作系统用户、具有为Windows操作系统用户检索文件系统数据的适当权限、必须包括域前缀。



 a| 
Password
 a| 
操作系统用户的密码



 a| 
计算资源组
 a| 
用于标记数据源的主机和虚拟机的标注值将发现文件系统。空值表示数据源将发现当前未标注任何计算资源组的所有主机和虚拟机的文件系统。

|===


== 高级配置

|===


| 字段 | Description 


 a| 
清单轮询间隔（分钟）
 a| 
两次清单轮询的间隔(默认值为360分钟)

|===