---
permalink: config-admin/predefined-annotation-types.html 
sidebar: sidebar 
keywords:  
summary: OnCommandInsight提供了一些默认标注类型。这些标注可用于筛选或分组数据以及筛选数据报告。 
---
= 默认标注类型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommandInsight提供了一些默认标注类型。这些标注可用于筛选或分组数据以及筛选数据报告。

您可以将资产与以下默认标注类型关联：

* 资产生命周期，例如，生日，日出或生命周期结束
* 有关设备的位置信息，例如数据中心，建筑物或楼层
* 按质量（层），已连接设备（交换机级别）或服务级别等对资产进行分类
* 状态，例如热（高利用率）


下表列出了默认标注类型。您可以根据需要编辑其中任何标注名称。

|===


| 标注类型 | Description | Type 


 a| 
别名
 a| 
资源的用户友好名称。
 a| 
文本



 a| 
生日
 a| 
设备已联机或将联机的日期。
 a| 
Date



 a| 
构建
 a| 
主机、存储、交换机和磁带资源的物理位置。
 a| 
列表



 a| 
城市
 a| 
主机、存储、交换机和磁带资源的市政位置。
 a| 
列表



 a| 
计算资源组
 a| 
主机和VM文件系统数据源使用的组分配。
 a| 
列表



 a| 
大陆
 a| 
主机、存储、交换机和磁带资源的地理位置。
 a| 
列表



 a| 
国家 / 地区
 a| 
主机、存储、交换机和磁带资源的国家位置。
 a| 
列表



 a| 
数据中心
 a| 
资源的物理位置、可用于主机、存储阵列、交换机和磁带。
 a| 
列表



 a| 
直连
 a| 
指示(是或否)存储资源是否直接连接到主机。
 a| 
布尔值



 a| 
生命周期结束
 a| 
设备脱机的日期、例如租约到期或硬件停用。
 a| 
Date



 a| 
网络结构别名
 a| 
网络结构的用户友好名称。
 a| 
文本



 a| 
楼层
 a| 
设备在建筑物楼层的位置。可以为主机、存储阵列、交换机和磁带设置。
 a| 
列表



 a| 
热
 a| 
设备已定期频繁使用或已达到容量阈值。
 a| 
布尔值



 a| 
注意
 a| 
要与资源关联的注释。
 a| 
文本



 a| 
机架
 a| 
资源所在的机架。
 a| 
文本



 a| 
房间
 a| 
主机、存储、交换机和磁带资源位于建筑物或其他位置的房间。
 a| 
列表



 a| 
SAN
 a| 
网络的逻辑分区。适用于主机、存储阵列、磁带、交换机和应用程序。
 a| 
列表



 a| 
服务级别
 a| 
一组可分配给资源的受支持服务级别。提供内部卷， qtree 和卷的有序选项列表。编辑服务级别以设置不同级别的性能策略。
 a| 
列表



 a| 
省/自治区/直辖市
 a| 
资源所在的省/自治区/直辖市。
 a| 
列表



 a| 
《日出》
 a| 
设置的阈值，超过此阈值后，无法为该设备进行新分配。适用于计划内迁移和其他待定网络更改。
 a| 
Date



 a| 
交换机级别
 a| 
包括用于设置交换机类别的预定义选项。通常、这些指定值在设备生命周期内保持不变、但您可以根据需要对其进行编辑。仅适用于交换机。
 a| 
列表



 a| 
层
 a| 
可用于定义环境中的不同服务级别。层可以定义级别的类型，例如所需的速度（例如金牌或银牌）。此功能仅适用于内部卷， qtree ，存储阵列，存储池和卷。
 a| 
列表



 a| 
违规严重性
 a| 
在重要性从高到低的层次结构中对违规（例如，缺少主机端口或缺少冗余）进行排名（例如，重大）。
 a| 
列表

|===
[NOTE]
====
别名、数据中心、热、服务级别、Sunset、 交换机级别、服务级别、层和违规严重性均为系统级别标注、您无法删除或重命名这些标注；您只能更改其分配的值。

====