---
permalink: config-admin/scrubbing-data-for-transfer-to-support-webui.html 
sidebar: sidebar 
keywords:  
summary: '拥有安全环境的客户需要与NetApp客户服务进行通信、以便在不影响其数据库信息的情况下对出现的问题进行故障排除。通过OnCommand Insight 擦洗实用程序、您可以设置一个包含关键字和模式的综合词典、以便"清理"敏感数据并将擦洗的文件发送给客户支持。' 
---
= 擦洗数据以传输到支持部门
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
拥有安全环境的客户需要与NetApp客户服务进行通信、以便在不影响其数据库信息的情况下对出现的问题进行故障排除。通过OnCommand Insight 擦洗实用程序、您可以设置一个包含关键字和模式的综合词典、以便"清理"敏感数据并将擦洗的文件发送给客户支持。



== 步骤

. 在Web UI中、单击*管理*并选择*故障排除*。
. 在页面底部的其他任务区域中、单击*擦洗实用程序*链接。
+
擦除部分有几个：在词典中查找、擦除数据和构建词典、自定义关键字和正则表达式。

. 
+
.. 在"*在词典中查找"*部分中、输入一个代码以显示其替换的值、或者输入一个值以查看替代该值的代码。注意：在执行查找之前、必须*构建*词典以标识要从支持数据中擦除的值。


. 要添加您自己的关键字以从支持数据中擦除、请在*自定义关键字*部分中单击菜单：操作[添加自定义关键字]。输入关键字并单击*保存*。此关键字将添加到词典中。
. 展开*模式(regexp)*。单击*添加*以显示用于输入新模式的对话框。
. 要使用正则表达式来标识要擦除的词或短语、请在*正则表达式*部分中输入一个或多个模式。单击菜单：操作[添加正则表达式]、在字段中输入模式名称和正则表达式、然后单击*保存*。此信息已添加到词典中。
+
[NOTE]
====
模式必须包含在圆括号中、才能标识正则表达式捕获组。

====
. 在"*构建词典"*部分中、单击*构建*以对OnCommand Insight 数据库中标识为敏感的所有词启动词典编译。
+
完成后、您会看到一个提示、告知您修订后的词典可用。Database问题描述 包含一条线、用于指示词典中的关键字数量。检查词典中的关键字是否准确。如果您发现问题并希望重建词典、请单击数据库块上的*重置*以从词典中删除从OnCommand Insight 数据库收集的所有关键字。如提示所述、不会删除任何其他关键字。返回到擦除实用程序、然后重新输入自定义关键字。

. 创建擦除词典后、您可以使用它擦除日志、XML或其他文本文件以使数据匿名。
. 要擦除日志、XML或其他文本文件、请在*擦除数据*部分中浏览找到该文件、然后单击*擦除文件*。

