---
permalink: reporting/oncommand-insight-data-model-descriptions.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 包含多个数据模型、您可以从中选择预定义报告或创建自己的自定义报告。 
---
= OnCommand Insight 数据模型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 包含多个数据模型、您可以从中选择预定义报告或创建自己的自定义报告。

每个数据模型都包含一个简单的数据集市和一个高级数据集市：

* 通过简单数据集市、可以快速访问最常用的数据元素、并且仅包含数据仓库数据的最后一个快照；它不包含历史数据。
* 高级数据集市可提供简单数据集市中提供的所有值和详细信息、并可访问历史数据值。
* *容量数据模型*
+
用于问题解答存储容量，文件系统利用率，内部卷容量，端口容量， qtree 容量， 和虚拟机（ VM ）容量。容量数据模型是一个用于多个容量数据模型的容器。您可以使用此数据模型创建报告来回答各种类型的问题：

+
** *存储和存储池容量数据模型*
+
用于回答有关存储容量资源规划（包括存储和存储池）的问题解答问题，其中包括物理和虚拟存储池数据。这种简单的数据模型可以帮助您解决问题解答中有关楼层容量以及存储池在一段时间内按层和数据中心的容量使用情况的问题。

+
如果您刚开始使用容量报告，则应先使用此数据模型，因为它是一个更简单，有针对性的数据模型。您可以使用此数据模型对类似以下内容的问题进行问题解答处理：

+
*** 达到物理存储 80% 容量阈值的预计日期是什么？
*** 阵列上给定层的物理存储容量是多少？
*** 按制造商和系列以及数据中心显示的存储容量是多少？
*** 所有层的阵列上的存储利用率趋势是什么？
*** 利用率最高的前 10 个存储系统是什么？
*** 存储池的存储利用率趋势是什么？
*** 已分配多少容量？
*** 可分配哪些容量？


** *文件系统利用率数据模型*
+
用于问题解答 文件系统利用率问题。此数据模型可按主机在文件系统级别查看容量利用率。管理员可以确定每个文件系统的已分配和已用容量，确定文件系统的类型，并按文件系统类型确定趋势统计信息。您可以问题解答使用此数据模型回答以下问题：

+
*** 文件系统的大小是多少？
*** 数据保存在何处，如何访问，例如本地或 SAN ？
*** 文件系统容量的历史趋势是什么？那么，基于这一点，我们可以为未来需求预测哪些内容？


** *内部卷容量数据模型*
+
用于问题解答有关内部卷已用容量，已分配容量以及一段时间内的容量使用情况的问题：

+
*** 哪些内部卷的利用率高于预定义的阈值？
*** 根据趋势，哪些内部卷可能会用尽容量？
*** 内部卷上的已用容量与已分配容量是多少？


** *端口容量数据模型*
+
用于问题解答有关交换机端口连接，端口状态和端口速度随时间变化的问题。您可以通过问题解答 提出类似以下内容的问题来帮助您规划购买新交换机的计划：

+
*** 如何创建端口消耗预测来预测资源(端口)可用性(根据数据中心、交换机供应商和端口速度)？
*** 哪些端口可能会用尽容量，从而提供数据速度，数据中心，供应商以及主机和存储端口的数量？
*** 交换机端口容量随时间的变化趋势是什么？
*** 端口速度是多少？
*** 需要哪种类型的端口容量？哪个组织即将用尽特定端口类型或供应商的容量？
*** 购买该容量并使其可用的最佳时间是什么？


** * qtree容量数据模型*
+
用于趋势化 qtree 利用率（使用已用容量与已分配容量等数据）随时间的变化。您可以按不同维度查看信息、例如、按业务实体、应用程序、层和服务级别。您可以问题解答使用此数据模型回答以下问题：

+
*** qtree 的已用容量与每个应用程序或业务实体设置的限制是多少？
*** 我们的已用容量和可用容量的趋势是什么，以便我们能够进行容量规划？
*** 哪些业务实体使用的容量最多？
*** 哪些应用程序占用的容量最多？


** *虚拟机容量数据模型*
+
用于报告虚拟环境及其容量使用情况。通过此数据模型，您可以报告 VM 和数据存储的容量使用情况随时间的变化。此数据模型还提供精简配置和虚拟机成本分摊数据。

+
*** 如何根据为 VM 和数据存储配置的容量确定容量成本分摊？
*** VM 不使用哪些容量？未使用的容量中有哪些部分是可用容量，哪些部分是孤立容量或其他容量？
*** 根据消费趋势，我们需要购买哪些产品？
*** 使用存储精简配置和重复数据删除技术可以节省多少存储效率？VM 容量数据模型中的容量来自虚拟磁盘（ VMDK ）。这意味着，使用 VM 容量数据模型的 VM 的已配置大小等于其虚拟磁盘的大小。这与OnCommand Insight 虚拟机视图中的已配置容量不同、该视图显示了VM本身的已配置大小。


** *卷容量数据模型*
+
用于分析环境中卷的所有方面，并按供应商，型号，层，服务级别和数据中心组织数据。您可以查看与孤立卷，未使用的卷和保护卷（用于复制）相关的容量。您还可以查看不同的卷技术（ iSCSI 或 FC ），并比较虚拟卷与非虚拟卷以解决阵列虚拟化问题。对于此数据模型，您可以问题解答回答类似于以下内容的问题：

+
*** 哪些卷的利用率高于预定义的阈值？
*** 我的数据中心中孤立卷容量的趋势是什么？
*** 我的数据中心容量中有多少是虚拟化或精简配置的？
*** 必须为复制预留多少数据中心容量？




* *成本分摊数据模型*
+
用于问题解答存储资源（卷，内部卷和 qtree ）上有关已用容量和已分配容量的问题。此数据模型按主机，应用程序和业务实体提供存储容量成本分摊和责任信息，其中包括当前数据和历史数据。报告数据可以按服务级别和存储层进行分类。

+
您可以使用此数据模型通过查找业务实体使用的容量来生成成本分摊报告。通过此数据模型，您可以为多个协议（包括 NAS ， SAN ， FC 和 iSCSI ）创建统一报告。

+
** 对于没有内部卷的存储，成本分摊报告将按卷显示成本分摊。
** 对于具有内部卷的存储：
+
*** 如果将业务实体分配给卷，成本分摊报告将按卷显示成本分摊。
*** 如果业务实体未分配给卷，而是分配给 qtree ，则成本分摊报告将按 qtree 显示成本分摊。
*** 如果业务实体未分配给卷，也未分配给 qtree ，成本分摊报告将显示内部卷。
*** 决定是否按卷， qtree 或内部卷显示成本分摊是根据每个内部卷进行的，因此同一存储池中的不同内部卷可能会在不同级别显示成本分摊。容量数据会在默认时间间隔后清除。有关详细信息，请参见数据仓库流程。




+
使用成本分摊数据模型的报告显示的值可能与使用存储容量数据模型的报告显示的值不同。

+
** 对于非 NetApp 存储系统的存储阵列，来自两个数据模型的数据是相同的。
** 对于 NetApp 和 Celerra 存储系统，成本分摊数据模型使用单个层（卷，内部卷或 qtree ）来确定成本，而存储容量数据模型使用多个层（卷和内部卷）来确定成本。


* *清单数据模型*
+
用于问题解答有关清单资源的问题，包括主机，存储系统，交换机，磁盘，磁带， qtree ，配额，虚拟机和服务器以及通用设备。清单数据模型包含多个子集市，可用于查看有关复制， FC 路径， iSCSI 路径， NFS 路径和违规的信息。清单数据模型不包括历史数据。您可以通过问题解答 处理此数据集市的问题包括：

+
** 我拥有哪些资产，这些资产位于何处？
** 谁在使用这些资产？
** 我拥有哪些类型的设备，这些设备的组件是什么？
** 每个操作系统有多少台主机，这些主机上有多少个端口？
** 每个供应商在每个数据中心都有哪些存储阵列？
** 每个供应商在每个数据中心有多少个交换机？
** 有多少端口未获得许可？
** 我们正在使用哪些供应商磁带、每个磁带上有多少个端口？
** 在我们开始处理报告之前、是否已确定所有通用设备？
** 主机与存储卷或磁带之间的路径是什么？
** 通用设备与存储卷或磁带之间的路径是什么？
** 每个数据中心有多少次每种类型的违规？
** 对于每个复制的卷，源卷和目标卷是什么？
** 光纤通道主机 HBA 和交换机之间是否存在任何固件不兼容或端口速度不匹配的情况？


* *性能数据模型*
+
用于问题解答有关卷，应用程序卷，内部卷，交换机，应用程序， VM ， VMDK ， ESX 与 VM ，主机和应用程序节点的对比。使用此数据模型，您可以创建报告，说明问题解答有多种类型的性能管理问题：

+
** 在特定时间段内，哪些卷或内部卷未使用或访问？
** 我们是否可以确定某个应用程序（未使用）的存储配置是否存在任何潜在的错误？
** 应用程序的整体访问行为模式是什么？
** 是否为给定应用程序正确分配了分层卷？
** 对于当前运行的应用程序，我们是否可以在不影响应用程序性能的情况下使用更便宜的存储？
** 哪些应用程序正在对当前配置的存储进行更多访问？使用交换机性能表时，您可以获取以下信息：
** 通过连接的端口传输的主机流量是否平衡？
** 哪些交换机或端口出现大量错误？
** 根据端口性能，最常用的交换机是什么？
** 根据端口性能，哪些交换机未充分利用？
** 根据端口性能，主机吞吐量的趋势是什么？
** 一个指定主机，存储系统，磁带或交换机过去 X 天的性能利用率是多少？
** 哪些设备在特定交换机上生成流量（例如，哪些设备负责使用利用率高的交换机）？
** 环境中特定业务单位的吞吐量是多少？使用磁盘性能表时，您可以获取以下信息：
** 根据磁盘性能数据，指定存储池的吞吐量是多少？
** 使用率最高的存储池是什么？
** 特定存储的平均磁盘利用率是多少？
** 根据磁盘性能数据，存储系统或存储池的使用趋势是什么？
** 特定存储池的磁盘使用趋势是什么？使用 VM 和 VMDK 性能表时，您可以获取以下信息：
** 我的虚拟环境是否性能最佳？
** 哪些 VMDK 报告的工作负载最高？
** 如何使用从映射到不同数据存储库的 VMD 报告的性能来决定重新分层。性能数据模型包含的信息可帮助您确定层的适当性，应用程序的存储配置不当以及卷和内部卷的上次访问时间。此数据模型可提供响应时间， IOPS ，吞吐量，待处理写入次数和访问状态等数据。


* *存储效率数据模型*
+
可用于跟踪存储效率得分和随时间变化的潜力。此数据模型不仅存储已配置容量的测量值，还存储已用或已用容量的测量值（物理测量值）。例如、启用精简配置时、OnCommand Insight 指示从设备中获取的容量。您也可以使用此模型来确定启用重复数据删除时的效率。您可以问题解答使用存储效率数据集市回答各种问题：

+
** 实施精简配置和重复数据删除技术可以节省多少存储效率？
** 数据中心之间的存储节省量是多少？
** 根据历史容量趋势，我们何时需要购买更多存储？
** 如果我们启用了精简配置和重复数据删除等技术，容量会增加多少？
** 关于存储容量，我现在是否面临风险？



