---
permalink: reporting/which-report-answers-your-question.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 包含预定义报告、可满足多种常见报告要求、为利益相关方提供必要的重要见解、帮助他们做出明智的存储基础架构决策。 
---
= 使用预定义报告解决问题解答常见问题
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 包含预定义报告、可满足多种常见报告要求、为利益相关方提供必要的重要见解、帮助他们做出明智的存储基础架构决策。

以下预定义报告可在*团队内容*>*报告*或*团队内容*>*供应商专用报告*中找到。

NetApp Storage Automation Store可能提供更新版本的报告。您应定期查看Automation Store中的报告。

* * AWS云成本数据*
+
云成本报告提供了所有资产的整合视图、您可以跟踪、分析和优化基于云的服务以及内部服务在环境中动态扩展时的使用情况和成本。

+
该报告提供了基础架构与成本之间的关联、可提供清晰且可操作的报告、以确保通过重点明确的容量规划和浪费检测实现合理的规模估算。

* *应用程序服务级别容量和性能*
+
" 应用程序服务级别容量和性能 " 报告简要概述了应用程序。您可以将此信息用于容量规划或迁移计划。

* *成本分摊*
+
成本分摊报告按主机，应用程序和业务实体提供存储容量成本分摊和成本核算信息，其中包括当前数据和历史数据。

+
为防止重复计数，请勿包含 ESX 服务器，只监控 VM 。

+
此报告的更新版本可从 NetApp 存储自动化商店获得。

* *数据源*
+
" 数据源 " 报告显示站点上安装的所有数据源，数据源的状态（成功 / 失败）以及状态消息。此报告提供了有关从何处开始对数据源进行故障排除的信息。失败的数据源会影响Insight报告的准确性以及产品的一般可用性。

* * ESX与VM性能*
+
ESX 与 VM 性能报告对 ESX 服务器和 VM 进行了比较，显示了 ESX 服务器和 VM 的平均和峰值 IOPS ，吞吐量以及延迟和利用率。为防止重复计数，请排除 ESX 服务器；仅包括 VM 。

+
此报告的更新版本可从 NetApp 存储自动化商店获得。

* *网络结构摘要*
+
Fabric Summary 报告可确定交换机和交换机信息，包括端口数量，固件版本和许可证状态。此报告不包括 NPV 交换机端口。

* *主机HBA*
+
主机 HBA 报告概述了环境中的主机，并提供了 HBA 的供应商，型号和固件版本以及它们所连接的交换机的固件级别。在为交换机或 HBA 规划固件升级时，此报告可用于分析固件兼容性。

* *主机服务级别容量和性能*
+
" 主机服务级别容量和性能 " 报告按主机概括介绍了纯块应用程序的存储利用率。

* *主机摘要*
+
" 主机摘要 " 报告概述了每个选定主机的存储利用率，并提供了有关光纤通道和 iSCSI 主机的信息。此报告可用于比较端口和路径，光纤通道和 iSCSI 容量以及违规计数。

* *许可证详细信息*
+
" 许可证详细信息 " 报告显示了在具有活动许可证的所有站点中您获得许可的授权资源数量。此报告还显示具有活动许可证的所有站点的实际数量总和。此总和可能包括由多个服务器管理的存储阵列的重叠。

* *已映射但未屏蔽卷*
+
" 已映射但未屏蔽的卷 " 报告列出逻辑单元号（ LUN ）已映射以供特定主机使用但未屏蔽到该主机的卷。在某些情况下，这些 LUN 可能是已取消使用的未屏蔽 LUN 。未屏蔽的卷可由任何主机访问，因此容易受到数据损坏的影响。

* * NetApp容量和性能*
+
NetApp 容量和性能报告提供有关已分配，已利用和已提交容量的全局数据，以及 NetApp 容量的趋势和性能数据。

* * OCI记分卡*
+
OCI记分卡报告提供了OnCommand Insight 发现的所有资产的摘要和常规状态。状态以绿色，黄色和红色标志表示：

+
** 绿色表示正常情况
** 黄色表示环境中可能存在问题描述
** 红色表示需要关注的问题描述 报告中的所有字段均在报告随附的数据字典中进行了说明。


* *存储摘要*
+
" 存储摘要 " 报告提供了原始容量，已分配容量，存储池和卷的已用容量和未用容量数据的全局摘要。此报告概述了所发现的所有存储。

+
此报告的更新版本可从NetApp Storage Automation Store获得。

* *虚拟机容量和性能*
+
介绍虚拟机（ VM ）环境及其容量使用情况。要查看某些数据，必须启用 VM 工具，例如 VM 关闭时。

* *虚拟机路径*
+
VM 路径报告提供了数据存储容量数据和性能指标，其中包括哪个虚拟机正在哪个主机上运行，哪些主机正在访问哪些共享卷，什么是活动访问路径以及容量分配和使用情况。

* *按精简池划分的HDS容量*
+
"HDS Capacity by Thin Pool" 报告显示了精简配置存储池上的可用容量。

* *按聚合划分的NetApp容量*
+
NetApp Capacity by Aggregate 报告显示聚合的原始总空间，总空间，已用空间，可用空间和已提交空间。

* *厚阵列的Symmetrix容量*
+
Symmetrix Capacity by Thick Array 报告显示了原始容量，可用容量，可用容量，已映射，已屏蔽， 和总可用容量。

* *精简池的Symmetrix容量*
+
"Symmetrix Capacity by Thin Pool" 报告显示了原始容量，可用容量，已用容量，可用容量，已用百分比， 已订阅容量和订阅率。

* *按阵列划分的XIV容量*
+
XIV Capacity by Array 报告显示了该阵列的已用和未用容量。

* 按池划分的*十四个容量*
+
"XIV Capacity by Pool" 报告显示了存储池的已用和未用容量。


