---
permalink: install-windows/anomaly-detection-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: 异常检测软件需要特定的操作系统、内存量、CPU核心和磁盘空间。要成功安装异常检测软件、您必须遵守某些要求。 
---
= 异常检测要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
异常检测软件需要特定的操作系统、内存量、CPU核心和磁盘空间。要成功安装异常检测软件、您必须遵守某些要求。

|===


| 组件 | Required 


 a| 
操作系统
 a| 
一台运行以下任一许可版本且未运行任何其他应用程序级别软件的计算机：

* Red Hat Enterprise Linux 7.3、7.4、7.5、7.6、7.7、 7.8、7.9、8.1、8.2、8.3、 8.4、8.5
* CentOS 7.5、7.6、7.7、7.8、7.9、 CentOS 8流
* Oracle Enterprise Linux 7.5、7.6、7.7、7.8、7.9、 8.1、8.2、8.3、8.4、8.5
* SUSE Enterprise Linux 15.1.、15.2.、15.3
* OpenSUSE 15.1.、15.2.、15.3


许可版本可确保安装所需的依赖关系由操作系统自动解决。

建议使用专用服务器。



 a| 
虚拟机(VM)
 a| 
如果为实例预留了CPU和内存资源、则异常检测可以在虚拟环境中运行。



 a| 
CPU和内存
 a| 
8核。64 GB内存服务器。



 a| 
可用磁盘空间
 a| 
服务器需要200 GB的可用磁盘空间、分区如下：

* 150 GB `/var/lib`
* 25 GB英寸 `/var/log`
* 25 GB英寸 `/opt`


软件安装需要以下磁盘空间：

* 5 GB英寸 `/var/lib`
* 25 GB英寸 `/var/log`
* 25 GB英寸 `/opt`


最佳做法是挂载 ``/opt``和 位于与根文件系统不同的磁盘上 (`/`）。



 a| 
权限
 a| 
安装异常检测软件需要sudo权限。



 a| 
网络
 a| 
要安装异常检测软件的Insight服务器必须与运行异常检测引擎的服务器位于同一网络上、或者至少位于同一站点或数据中心。异常检测软件不支持在广域网(Wide Area Network、WAN)中进行配置。

必须在VM上打开TCP端口8080和9200。



 a| 
前提条件
 a| 
您必须具有有效的Perform许可证。您必须具有要安装异常检测软件的Insight服务器的IP地址。

如果不接受默认端口、则Insight服务器上必须有备用端口号。

必须在VM上打开TCP端口8080和9200。

您必须为具有虚拟机管理员权限的帐户提供用户名和密码。

您必须为包含单个反斜杠(company\user)的用户名输入两个反斜杠(company\\user)。

用户名不能包含反斜杠(company\\tom)后面的"`t`"。

|===
[NOTE]
====
您必须与NetApp代表讨论并验证所有规模估算建议。

====