---
permalink: install-linux/insight-server-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: 建议使用专用服务器。请勿在安装了任何其他应用程序的服务器上安装Insight。物理服务器和虚拟服务器均受支持、但前提是满足产品要求。 
---
= Insight服务器要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建议使用专用服务器。请勿在安装了任何其他应用程序的服务器上安装Insight。物理服务器和虚拟服务器均受支持、但前提是满足产品要求。

要安装OnCommand Insight 服务器软件、您必须具有sudo权限。

某些Insight组件在安装期间可能需要依赖软件包。在安装Insight之前、请确保YUM存储库可访问。

[NOTE]
====
OnCommand Insight 的规模估算具有多种依赖关系、例如数据源类型和大小、环境中的资产数量、轮询间隔等。以下规模估算示例仅供参考；它们表示已对Insight进行测试的某些环境。更改环境中的上述任何因素或其他因素都可能会更改Insight的规模估算要求。这些准则包括最多可容纳90天性能归档数据的磁盘空间。

====
在安装或升级Insight之前、建议联系您的销售工程师以获取详细的规模估算指导。

*示例：*

|===


| 环境因素： | 测试的磁盘空间、CPU和内存： 


 a| 
80个存储阵列4、000个卷

4、000个VM

4、000个交换机端口
 a| 
250 GB磁盘空间8个核心

32 GB RAM



 a| 
160个存储阵列40、000个卷

8、000个VM

8、000个交换机端口
 a| 
1 TB磁盘空间12个核心

48 GB RAM

|===
*要求：*

|===


| 组件 | Required 


 a| 
操作系统
 a| 
一台运行以下任一许可版本且未运行任何其他应用程序级别软件的计算机：

* Red Hat Enterprise Linux 7.3、7.4、7.5、7.6、7.7、 7.8、7.9、8.1、8.2、8.3、 8.4、8.5
* CentOS 7.2、7.5、7.6、7.7、7.8、 7.9、CentOS 8流
* Oracle Enterprise Linux 7.5、7.6、7.7、7.8、7.9、 8.1、8.2、8.3、8.4、8.5


许可版本可确保安装所需的依赖关系由操作系统自动解决。

在安装Insight之前、您必须卸载MariaDB。

[NOTE]
====
卸载MariaDB还会删除Postfix邮件传输代理。

====
建议使用专用服务器。



 a| 
虚拟机(VM)
 a| 
如果为实例预留了CPU和内存资源、则此组件可以在虚拟环境中运行。



 a| 
内存和CPU
 a| 
24 - 256 GB RAM

8到32个核心



 a| 
可用磁盘空间
 a| 
100 GB—3 TB安装磁盘空间

50 GB—1 TB性能归档磁盘空间

对于500 GB的示例环境、建议按以下分区细分：

* /opt目录—50 GB
* /var/log目录—100 GB
* /var/lib目录—350 GB


最佳做法是挂载 `/opt` 和 `/var` 位于与根文件系统不同的磁盘上 (`/`）。

建议将SSD磁盘用于Insight安装空间。



 a| 
网络
 a| 
以太网连接和端口：

* 100 Mbps或1 Gbps以太网连接、具有专用(静态) IP地址和与SAN中所有组件(包括FC设备和远程采集单元)的IP连接。
* OnCommand Insight 服务器进程的端口要求为80、443、1090到1100、3873、8083、 4444到4446、5445、5455、4712到4714、5500、 和5501。
* 采集过程的端口要求为12123和5679。
* MySQL的端口要求为3306。
* Elasticsearch的端口要求为9200和9310


端口443和3306需要通过任何防火墙进行外部访问。



 a| 
权限
 a| 
需要对OnCommand Insight 服务器具有sudo权限。

如果以下任一文件夹为符号链接、请确保目标目录具有"755"权限。

* /opt/netapp
* /var/lib/netapp
* /var/log/netapp




 a| 
远程连接
 a| 
Internet连接、用于访问WebEx或远程桌面连接、以方便安装和安装后支持。



 a| 
可访问性
 a| 
需要HTTPS访问。



 a| 
HTTP或HTTPS服务器
 a| 
Apache HTTP服务器或其他HTTPS服务器不应与OnCommand Insight 服务器争用相同的端口(443)、并且不应自动启动。如果它们必须侦听端口443、则必须将OnCommand Insight 服务器配置为使用其他端口。

|===