---
permalink: install-linux/installing-a-remote-acquisition-unit-rau-linux.html 
sidebar: sidebar 
keywords:  
summary: '您可以在OnCommand Insight 环境中安装一个或多个远程采集单元(RAU)。采集单元在网络中运行、通过称为数据源的模块访问\并从数据中心的不同设备收集数据。' 
---
= 安装远程采集单元
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在OnCommand Insight 环境中安装一个或多个远程采集单元(RAU)。采集单元在网络中运行、通过称为data_sources_的模块进行访问、并从数据中心的不同设备收集数据。



== 开始之前

您必须已完成所有安装前提条件。

RAU服务器和OnCommand Insight 服务器之间必须至少有一个端口处于打开状态且可用、才能将更改信息转发到服务器。如果您对此不确定、请在RAU计算机上打开Web浏览器并将其定向到OnCommand Insight 服务器、以对其进行验证：

[listing]
----
 https://< OnCommand Insight Server hostname >:< acquisition_port >
----
采集端口默认为443、但可能已在服务器安装期间发生更改。如果连接成功、您将看到OnCommand Insight 响应页面、指示RAU和OnCommand Insight 服务器之间打开且可用的端口。

对于使用网络地址转换或端口地址转换(NAT/PAT：即IP地址的任何转换)的环境、Insight仅支持在NAT和设备之间插入RAU。

* 支持：OnCommand Insight \-> NAT \-> RAU \->设备
* 不支持：OnCommand Insight \\-> RAU \\>NAT \\->设备




== 步骤

. 使用具有sudo权限的帐户登录到RAU服务器。
. 导航到安装文件所在的服务器上的目录、然后键入以下命令：
+
`unzip oci-rau-<version>-linux-x86_64.zip`

. 您可以查看的语法、命令参数和参数用法 `oci-install.sh`：
+
`sudo ./oci-rau-<version>-linux-x86_64/oci-install.sh --help`

. 运行安装脚本：
+
`sudo ./oci-rau-<version>-linux-x86_64/oci-install.sh`

. 阅读并接受许可协议、然后按照提示进行操作。
+
在问题解答 所有提示后、安装将开始、并且大约需要10分钟、具体取决于所安装的应用程序。


