---
permalink: install-linux/installing-an-ethernet-monitoring-unit-linux.html 
sidebar: sidebar 
keywords:  
summary: '"以太网监控单元"(emus\)可检查环境中的网络数据包、以便对从主机到存储资源的网络流量进行性能故障排除。' 
---
= 安装以太网监控单元
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
"`以太网监控单元(EMU)可检查环境中的网络数据包、以便对从主机到存储资源的网络流量的性能进行故障排除。



== 开始之前

[NOTE]
====
OnCommand Insight 7.3.12及更高版本不支持以太网监控单元(EMU)。

====
您必须已完成所有安装前提条件。



== 步骤

. 使用具有sudo权限的帐户登录到EMU服务器。
. 导航到安装文件所在的服务器上的目录、然后键入以下命令：
+
`unzip oci-ethernet-<version>-linux-x86_64.zip`

+
其中 `<version>` 是在下载的文件名中指定的版本号。

. 您可以查看的语法、命令参数和参数用法 `oci-install.sh`：
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh --help`

. 运行安装脚本：
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh`

. 阅读并接受许可协议。
. 问题解答 每个提示符：
+
** * OnCommand Insight **服务器名称或IP地址*—用于标识OnCommand Insight 服务器的主机名或IP地址。EMU使用此名称/IP打开与服务器的通信链路。如果指定主机名、请确保可以通过DNS解析该主机名。
** *采集单元名称*—用于标识EMU的唯一名称。
** * OnCommand Insight 安全远程采集端口(HTTPS)*—EMU用于向OnCommand Insight 服务器发送环境更改信息的端口。此设置应与安装OnCommand Insight 服务器时输入的值匹配、并且在所有EMU上必须相同。
** *以太网PAS输出目录*-输入PAS输出的文件夹。
** *要监控的以太网PAS接口*-输入要监控其流量的接口。
** *启用巨型数据包*-如果客户环境使用巨型数据包、则EMU会创建大型数据包缓冲区来读取这些数据包。否则、EMU将使用可用内存池来存储标准以太网数据包。在问题解答 所有提示后、安装将开始、并且大约需要10分钟、具体取决于所安装的应用程序。



