---
permalink: dwh/annotations.html 
sidebar: sidebar 
keywords:  
summary: 通过标注、您可以定义与环境中的对象相关的信息、然后根据标注跟踪对象。例如、您可以将建筑物或楼层号标注添加到环境中的设备、然后创建一个查询以返回数据中心一层的所有设备。 
---
= 使用标注可以执行的操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过标注、您可以定义与环境中的对象相关的信息、然后根据标注跟踪对象。例如、您可以将建筑物或楼层号标注添加到环境中的设备、然后创建一个查询以返回数据中心一层的所有设备。

此外、您可能还需要查看特定数据中心或业务实体中的所有设备、并确定哪个业务实体使用的第1层存储最多。为此、您可以使用OnCommand Insight Web UI为设备分配数据中心、业务实体或层标注。然后、您可以将选定的用户定义标注从OnCommand Insight 导入到数据仓库中。要查看分配给对象的标注值显示在自定义报告中、您需要执行此操作。

您可以指定哪些用户定义的标注传播到数据仓库。标注将作为附加列添加到清单中的对象表以及数据集市中的相关维度表中。在使用OnCommand Insight 用户界面更新资源标注并启动或等待下一个数据仓库构建时、您会在下表中看到结果：

* dwh_inventory.annotation_value
* dwh_inventory.object_to_annotation


要确保在OnCommand Insight 中输入的标注包含在数据仓库中、需要执行以下主要过程：

* 在将标注导入到数据仓库之前、您必须确保已在OnCommand Insight 中准备好标注。
+
为此、您可以手动运行*故障排除*>*强制更新数据仓库的标注*选项、或者等待下一个计划的瞬时数据运行过程。在强制更新标注时、您可以强制OnCommand Insight 服务器计算瞬时数据(如标注值)并将其放置到数据库表中、以便数据仓库ETL进程可以读取数据。标注数据每十五分钟自动更新一次；但是、您可以强制更频繁地更新。

* 然后，使用“数据仓库**标注**选项将标注导入到数据仓库中。
* 如果要在使用OnCommand Insight 报告门户报告创作工具创建的报告中包含标注、则必须更新OnCommand Insight 报告元数据模型。


升级数据仓库时、标注作业会在数据库还原过程中自动运行。WildFly启动时、标注作业也会自动运行。

[NOTE]
====
WildFly是运行OnCommand Insight Java代码的应用程序服务器、OnCommand Insight 服务器和数据仓库都需要此应用程序服务器。

====