---
permalink: dwh/data-retention-and-time-periods.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight 数据仓库会根据不同的数据集市和数据的时间粒度、在不同的时间段内保留从提取、转换和加载\(ETL\)过程中获取的数据。' 
---
= 数据保留、ETL和时间段
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 数据仓库会根据数据的不同数据集市和时间粒度、将从提取、转换和加载(ETL)流程获取的数据保留不同时间段。



== 卷和内部卷的性能集市和每小时粒度

OnCommand Insight 数据仓库会记录14天内每天每小时的每小时平均值、每小时最大值和访问位(24个数据点)。访问位是一个布尔值、如果访问了卷、则为true；如果在每小时间隔内未访问卷、则为false。前一天的所有24个数据点都是在当天的第一个ETL过程中获取的。

您无需每小时运行一个ETL流程来收集每小时数据点。在一天内运行其他ETL进程不会从OnCommand Insight 服务器获取任何性能信息。



== 卷和内部卷的性能集市和每日粒度

每天处理ETL时、都会在数据仓库中计算和填充前一天的每日平均值。每日平均值是前一天24个数据点的汇总。性能数据集市会将卷和内部卷的每日摘要保留13个月。



== 容量集市和每日粒度

容量集市每天对13个月内的各种容量数据进行测量。数据仓库中的容量数据是在ETL之前最后一次为设备采集数据源时的最新数据。



== 容量集市和每月粒度

数据仓库会将每日容量数据保留13个月。达到13个月的阈值后、容量数据将按月汇总。每月数据基于月份代表性日期所反映的值。

下表显示了每月摘要中包含的每月数据：

|===


| Date | 为月份代表值 | 已分配容量 


 a| 
1月1日
 a| 
1 (正确)
 a| 
50 TB



 a| 
1月2日
 a| 
0 (错误)
 a| 
52 TB



 a| 
...
 a| 
...
 a| 
...



 a| 
1月31日
 a| 
0 (错误)
 a| 
65 TB



 a| 
2月1日
 a| 
1 (正确)
 a| 
65 TB

|===
根据该表、每月报告将显示1月份分配的容量为50 TB、2月份分配的容量为65 TB。1月份的所有其他容量值都不会包含在每月摘要中。



== 清单数据集市

清单数据集市不是历史数据集市。每次运行ETL进程时、都会擦除并重建清单数据集市。因此、从清单数据集市生成的任何报告都不会反映历史清单配置。
