---
permalink: dwh/reporting-user-roles.html 
sidebar: sidebar 
keywords:  
summary: 系统会为每个用户帐户分配一个具有一组权限的角色。用户数量受附加到每个角色的报告许可证数量的限制。 
---
= 报告用户角色
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
系统会为每个用户帐户分配一个具有一组权限的角色。用户数量受附加到每个角色的报告许可证数量的限制。

每个角色均可执行以下操作：

* *收件人*
+
查看OnCommand Insight 报告门户报告并设置个人首选项、例如语言和时区的首选项。

+
[NOTE]
====
收件人既不能创建报告、运行报告、计划报告、导出报告、也不能执行管理任务。

====
* *业务消费者*
+
运行报告并执行所有收件人选项。

* *业务作者*
+
除了执行所有业务消费者选项之外、还可以查看计划的报告、以交互方式运行报告、创建案例。

* *专业作者*
+
除了执行所有Business Author选项之外、还可以创建报告、创建软件包和数据模块。

* *管理员*
+
执行报告管理任务、例如导入和导出报告定义、配置报告、配置数据源以及关闭和重新启动报告任务。



下表显示了每个角色所允许的权限和最大用户数：

|===


| 功能 | 收件人 | 业务消费者 | 业务作者 | 专业作者 | 管理员 


 a| 
在 " 团队内容 " 选项卡中查看报告
 a| 
是的。
 a| 
是的。
 a| 
是的。
 a| 
是的。
 a| 
是的。



 a| 
运行报告
 a| 
否
 a| 
是的。
 a| 
是的。
 a| 
是的。
 a| 
是的。



 a| 
计划报告
 a| 
否
 a| 
是的。
 a| 
是的。
 a| 
是的。
 a| 
是的。



 a| 
上传外部文件
 a| 
否
 a| 
否
 a| 
是的。
 a| 
是的。
 a| 
否



 a| 
创建案例
 a| 
否
 a| 
否
 a| 
是的。
 a| 
是的。
 a| 
否



 a| 
创建报告
 a| 
否
 a| 
否
 a| 
是的。
 a| 
是的。
 a| 
否



 a| 
创建软件包和数据模块
 a| 
否
 a| 
否
 a| 
否
 a| 
是的。
 a| 
否



 a| 
执行管理任务
 a| 
否
 a| 
否
 a| 
否
 a| 
否
 a| 
是的。



 a| 
用户数
 a| 
OnCommand Insight 用户数
 a| 
20
 a| 
2.
 a| 
1.
 a| 
1.

|===
添加新的数据仓库和报告用户时、如果您超过某个角色的限制、则该用户将添加为"已激活、`d`"、您需要停用或删除具有此角色的其他用户、才能授予新用户成员资格。

[NOTE]
====
报告创作功能需要Insight Plan许可证。您可以通过购买arap (其他报告创作包)来添加其他业务作者和专业作者用户。请联系您的OnCommand Insight 代表以获得帮助。

====
这些报告用户角色不会影响直接数据库访问。这些报告用户角色不会影响您使用数据集市创建SQL查询的能力。
