---
permalink: howto/configuring-applications-for-your-company.html 
sidebar: sidebar 
keywords:  
summary: 了解公司环境中使用的应用程序有助于跟踪资产使用情况并报告成本。在此、我们将配置贵公司的应用程序并将其与相应的资产关联起来。 
---
= 为您的公司配置应用程序
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
了解公司环境中使用的应用程序有助于您跟踪资产使用情况并报告成本。在此、我们将配置贵公司的应用程序并将其与相应的资产相关联。



== 关于此任务

在_为您的公司配置业务实体_部分中、我们创建了一些业务实体、并建议您列出与每个业务实体关联的所有应用程序。然后、我们可以通过OnCommand Insight 跟踪与这些应用程序关联的数据、以获得使用情况或成本报告等信息。

在跟踪与环境中运行的应用程序关联的数据之前，您必须先定义这些应用程序并将其与相应的资产相关联。您可以将应用程序与以下资产相关联：主机，虚拟机，卷，内部卷， qtree ， 共享和虚拟机管理程序。

在本演练中、我们希望跟踪营销团队用于其Exchange电子邮件的虚拟机的使用情况。在定义业务实体时、您将记住我们创建的下表。我们在此工作表中添加一列、列出每个业务实体使用的应用程序。(此表仅为工作表示例。在Insight的业务实体表中、您不会看到"`应用程序`"列。)

|===


| 租户 | 业务部门 | 业务部门 | 项目 | 应用程序 


 a| 
NetApp
 a| 
数据存储
 a| 
法律
 a| 
专利
 a| 
Oracle Identity Manager ， Oracle On Demand ， PatentWiz



 a| 
NetApp
 a| 
数据存储
 a| 
营销
 a| 
销售活动
 a| 
Exchange ， Oracle 共享数据库， Blasoff Event Planner



 a| 
不适用
 a| 
不适用
 a| 
安全与保障
 a| 
不适用
 a| 
不适用



 a| 
...
 a| 
 a| 
 a| 
 a| 

|===
*在Insight中创建应用程序：*



== 步骤

. 以具有管理权限的用户身份登录到 Insight 。
. 选择*管理*>*应用程序*
. 单击*+添加*按钮
. 输入应用程序的名称(在本示例中、输入"`Exchange`")
. 选择应用程序的优先级
. 如果要将应用程序与业务实体关联、请从*业务实体*下拉列表中选择一个。否则、您可以将其保留为"`None`"。
. 如果要确保每个主机都可以访问集群中的相同卷、请确保选中*验证卷共享*复选框。例如、高可用性集群中的主机通常需要屏蔽到相同的卷才能进行故障转移；但是、不相关应用程序中的主机通常不需要访问相同的物理卷。此外、出于安全原因、监管策略可能要求您明确禁止不相关的应用程序访问相同的物理卷。如果不使用卷共享、请清除*验证卷共享*框。这需要Assure许可证。
. 单击保存。
. 对环境中的所有其他应用程序重复上述步骤。




== 完成后

我们发现营销团队使用Exchange应用程序。我们希望了解他们的Exchange虚拟机利用率、以便预测何时需要添加更多存储。让我们将Exchange应用程序与营销部门的所有VM相关联。要实现此目的、最简单的方法是通过查询。

通过执行以下步骤、您可以将每个应用程序与其相应的资产相关联。

*将应用程序与资产相关联：*

现在、您已经创建了应用程序(并根据需要将其绑定到业务实体)、我们可以将这些应用程序与您环境中的资产关联起来。在此示例中、我们将Exchange应用程序与贵公司的多个虚拟机相关联。执行此操作最简单的方法是查询。

. 选择*查询*>*+新建查询*。
. 在*选择资源类型*下拉列表中、选择_Virtual Machine_
. 我们会假定营销团队使用字符串"` mktg_`"为其资产命名。在名称筛选器框中、输入"` mktg_`"(不带引号)、然后单击应用(复选标记)按钮。
. 此时将显示包含"` mktg_`"字符串的所有虚拟机的列表。
. 如果需要、请单击*更多*下拉列表并添加其他筛选器。
. 单击每个所需VM名称旁边的复选框以选择用于Exchange的VM、或者单击列顶部的复选框以选择所有VM。
. 选择所需虚拟机后、单击*操作*按钮并选择*添加应用程序*。
. 在分配应用程序对话框中、单击*应用程序*下拉列表并选择"`Exchange`"。
. 单击 * 保存 * 。
. 根据需要重复此步骤、将Exchange应用程序与其他资产(主机、卷等)相关联

