---
permalink: howto/creating-policies-and-thresholds-for-storage-pools.html 
sidebar: sidebar 
keywords:  
summary: 您可以创建性能策略，以便在超过存储池资产阈值时触发警报以向您发出通知。 
---
= 为存储池创建性能策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以创建性能策略，以便在超过存储池资产阈值时触发警报以向您发出通知。



== 开始之前

此操作步骤假定您已对存储池进行精简配置。



== 关于此任务

您希望创建策略来监控和报告存储池中可能导致中断的更改。对于精简配置的物理存储池、您希望监控物理容量并监控过量使用比率。



== 步骤

. 在浏览器中打开OnCommand Insight。
. 选择*管理*>*性能策略*
+
此时将显示性能策略页面。策略按对象进行组织，并按其在列表中的显示顺序进行评估。如果启用了通知(*管理员*>*通知*)、则可以将Insight配置为在违反性能策略时发送电子邮件。

. 单击"**+Add"以创建新策略。
. 在*策略名称*中、输入存储池的策略名称。
. 在*应用于类型*的对象中、选择存储池。
. 在 * 应用后窗口 * 中，输入首次出现。
. 在 * 严重性 * 中输入严重
. 配置要在违反阈值时收到通知的电子邮件收件人。
+
默认情况下，有关策略违规的电子邮件警报会发送到全局电子邮件列表中的收件人。您可以覆盖这些设置，以便将特定策略的警报发送给特定收件人。

+
单击链接以打开收件人列表，然后单击 + 按钮以添加收件人。此策略的违规警报将发送到列表中的所有收件人。

. 在 * 如果以下任一项为 true ，则创建警报 * 中，输入 Capacity ratio - used > 85%




== 结果

此配置会导致系统在存储池的物理容量超过 85% 时发送严重警告消息。使用 100% 的物理内存将导致应用程序失败。



== 创建其他存储池策略



=== 关于此任务

创建一个额外的"`Capacity ratio - used`"策略、以便在已用存储池容量超过75%时发出警告消息。如果启用了通知(*管理员*>*通知*)、则可以将Insight配置为在违反性能策略时发送电子邮件。
