---
permalink: howto/creating-a-performance-policy-for-alerting.html 
sidebar: sidebar 
keywords:  
summary: 通过性能策略、您可以在满足特定条件时监控和发送警报。 
---
= 创建用于警报的性能策略
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过性能策略、您可以在满足特定条件时监控和发送警报。



== 关于此任务

在为资产添加标注后、我们可以创建一个性能策略、以便在Sunnyvale (DC1_SVL)数据中心的任何存储阵列的延迟超过2毫秒时向我们发出警报。如果出现这些情况、我们将向选定收件人发送一封电子邮件。



== 步骤

. 选择*管理*>*性能策略*。
+
此时将打开性能策略页面。已设置多个默认策略、您可以根据需要进行修改。但是、我们将创建一个新策略。

. 单击*+添加*按钮。
+
此时将打开*添加策略*对话框。

. 在*策略名称*字段中、输入"`Svl Data Center Latency policy`"。
+
您必须使用与对象的所有其他策略名称不同的名称。例如，不能为内部卷设置两个名为 " 延迟 " 的策略；但是，您可以为内部卷设置一个 " 延迟 " 策略，为其他卷设置另一个 " 延迟 " 策略。最佳做法是，无论对象类型如何，始终为任何策略使用唯一名称。

. 对于*应用于类型*的对象、选择*存储*。
. 在*带标注*字段中、选择*数据中心*为`Dc1_svl`(或在此处选择所需数据中心的名称)。
. 在*首次出现*窗口后应用。
+
首次出现选项会在第一个数据样本超过阈值时触发警报。所有其他选项都会在超过阈值一次且至少在指定时间内持续超过阈值时触发警报。

. 从*严重性*列表中、选择*警告*。
. 在*电子邮件收件人*下、单击以覆盖全局收件人列表。单击"++"*添加第一个所需警报收件人的电子邮件地址、然后单击*确定*。对任何其他所需的电子邮件收件人重复上述步骤。
. 如果下列条件中的*任何*为true、则保留创建警报的默认选项。此操作将在满足设置的任何一个阈值时发送警报。此外、您还可以选择仅在达到*所有*设置的阈值时才发出警报。
. 要设置第一个阈值、请在下拉列表中选择*延迟-总计*并将其设置为大于2毫秒。
. 如果需要、请单击*添加阈值*按钮添加要发出警报的其他阈值。按所需方式自定义策略后、单击*保存*。
. 您也可以选择*如果生成警报、则停止处理其他策略*。如果满足此策略的条件、此操作将暂停其他策略警报。
. 您可以根据业务需求添加任意数量的新策略、并根据不同的条件为其他收件人设置警报。如果配置的任何策略没有指定的收件人、则会向*管理员*>*通知*页面中设置的全局收件人列表发送警报




== 完成后

每个新策略在保存后都会自动激活、并且在满足策略的条件(称为_violation_）时、收件人将开始接收警报。您也可以在*信息板*>*违规信息板*中监控这些违规。
