---
permalink: howto/custom-dashboard-concepts.html 
sidebar: sidebar 
keywords:  
summary: 自定义信息板和小工具可以灵活地显示数据。以下是一些概念，可帮助您从自定义信息板中获得最大收益。以下各节将更详细地介绍每个概念。 
---
= 自定义信息板概念
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
自定义信息板和小工具可以灵活地显示数据。以下是一些概念，可帮助您从自定义信息板中获得最大收益。以下各节将更详细地介绍每个概念。

* 变量 *

通过变量，您可以一次性更改信息板上部分或所有小工具中显示的数据。通过将每个小工具设置为使用一个通用变量、在一个位置所做的更改发生原因 将每个小工具中显示的数据设置为自动更新。

*多个查询和/或表达式*

每个时间序列小工具(折线图、样条图、区域图或堆积分区图)最多可以包含五个查询和/或表达式、用于确定要显示的数据、从而可以比较单个图表上的不同数据集。例如、您可以使用一个折线图来显示存储和虚拟机的IOPS、也可以使用一个图表来比较所有存储池的吞吐量和延迟。

*汇总和分组*

每个小工具中显示的数据将从收集的数据点汇总起来。您可以选择通过以下几种方式之一汇总此数据：

* Avg：将数据汇总为基础数据的平均值
* Max：将数据汇总到基础数据的最大值
* Min：将数据汇总到基础数据的最小值
* Sum：将数据汇总为基础数据的总和


默认情况下、所有基础数据都会汇总到图表或表上的一个条目(全部)中。您可以选择改为为特定属性(如数据中心或层)汇总数据、以便将基础数据分发到所需的组中。您的小工具将仅显示所选属性的数据。

您可以根据所选属性对表小工具中的数据进行分组。例如、您可以选择按数据中心对表进行分组。可以随意展开或折叠组。表中的性能数据将根据您在小工具中设置的汇总方法(平均值、最大值、最小值或总和)汇总到组标题中。

表小工具可以按任意列进行排序、并且可以根据需要移动列或调整列大小。

*顶部/底部*

使用此选项可以限制图表小工具中的结果集、选择是在小工具中显示前N个结果、还是显示后N个结果。如果数据未汇总或按特定属性汇总、则可以选择此选项。

*覆盖信息板时间*

默认情况下、您添加到信息板中的大多数小工具都会根据信息板的时间范围设置(3小时、24小时、3天、7天、30天或自定义范围)显示数据。但是、您可以在各个小工具中覆盖此时间设置、以强制它们在特定时间上下文中显示数据、而不管信息板的时间设置如何。

下一节将更详细地介绍这些概念。
