---
permalink: howto/custom-dashboards.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 7.3包括增强的自定义信息板功能、可为用户提供对其重要的数据的操作视图、并提供该数据的一站式视图。 
---
= 创建自定义信息板
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 7.3包括增强的自定义信息板功能、可为用户提供对其重要的数据的操作视图、并提供该数据的一站式视图。

OnCommand Insight 允许用户使用多种小工具创建自定义信息板、每个小工具都可以灵活地显示和绘制数据、从而使用户可以灵活地创建跨IT平台的基础架构数据操作视图。在本操作说明中、我们将创建一个示例信息板以突出显示虚拟机性能。

此操作说明仅用作示例、并不涵盖所有可能的情形。本文中的概念和步骤可用于创建您自己的自定义信息板、以突出显示特定于您的特定需求的数据。

* 概述 *

您可以通过以下任一方法创建自定义信息板：

* *信息板*>*+新信息板*
* *信息板*>*显示所有信息板*、然后单击*+添加*


New Dashboard屏幕包含多个控件：

* *时间选择器*：允许您使用自定义日期范围选择器查看从3小时到90天不等的信息板数据。您可以选择在各个小工具中覆盖此全局时间范围。
* *编辑*按钮：选择"`on`"将启用编辑模式、以便对信息板进行更改。默认情况下，新信息板将在编辑模式下打开。
* *保存*按钮：用于保存、重命名或删除信息板。
* *变量*按钮：可以将变量添加到信息板中。更改变量将一次性更新所有小工具。有关变量的详细信息、请参见 link:custom-dashboard-concepts.md#["自定义信息板概念"]
* *小工具*按钮、用于向信息板添加任意数量的表、图表或其他小工具。


可以调整小工具的大小并将其重新定位到信息板中的不同位置，以便根据您的当前需求提供最佳的数据视图。

*小工具类型*

您可以从以下小工具类型中进行选择：

*表*小工具：根据您选择的筛选器和列显示数据的表。可以将表数据组合成可折叠和扩展的组。

*折线、Spline、Area、Stacked area*图表：这些是时间序列图表小工具、您可以在此小工具上显示一段时间内的性能和其他数据。

*单值*小工具：一个小工具、可用于显示一个值、该值可以直接从计数器派生、也可以使用查询或表达式计算得出。例如、您可以在信息板顶部以单个值的形式显示环境中所有存储的总IOPS之和。

*条形图*：用于显示前5、10、20或50个值的图表。

*方框图*图表：一个图表中数据的最小、最大、中值以及下四分位和上四分位之间的范围的图表。

*散点图*图表：将相关数据绘制为点、例如IOPS和延迟。在此示例中、您可以快速查看延迟较长且IOPS较低的资产。

此外、您还可以选择许多旧小工具。在*小工具*下拉列表中、选择"*显示更多..."*以查看这些小工具。
