---
permalink: howto/custom-dashboard-roll-up.html 
sidebar: sidebar 
keywords:  
summary: 信息板小工具中显示的数据是从所采集的数据点汇总的、这样可以在信息板中灵活而简洁地显示出来。 
---
= 汇总和聚合
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
信息板小工具中显示的数据是从所采集的数据点汇总的、这样可以在信息板中灵活而简洁地显示出来。

每个小工具中显示的数据都是从采集期间收集的底层数据点汇总的。例如，如果您有一个折线图小工具显示一段时间内的存储 IOPS ，则您可能希望为每个数据中心显示一条单独的行，以便进行快速比较。您可以选择通过以下几种方式之一汇总此数据：

* * 平均 * ：将每行显示为基础数据的 _average 。
* * 最大值 * ：将每行显示为基础数据的 _max_ 。
* * 最小 * ：将每行显示为基础数据的最小值。
* * 求和 * ：将每行显示为基础数据的 _sum_ 。


为此、请先在小工具的查询中选择资产类型(例如_Storage_)和指标(例如_IOPS - Tota_l)。对于*汇总*、请选择汇总方法(例如_Avg_)、然后选择用于汇总数据的属性或标注(例如_Data Center_)。此小工具会自动更新、并为每个数据中心显示一条线。

您也可以选择将底层数据汇总到图表或表中。在这种情况下、小工具中的每个查询都将显示一行、其中将显示所有底层资产的平均值、最小值、最大值或所选指标之和。

如果为查询设置了筛选器、则汇总的数据将基于筛选的数据。

请注意、如果您选择按任何字段(例如_Model_)汇总小工具、则仍需要*按*筛选该字段、以便在图表或表中正确显示该字段的数据。

*聚合数据：*在随后按属性(如果已选择)汇总数据之前、您可以通过将数据点聚合为分钟、小时或天分段来进一步对齐时间序列图表(折线图、区域图等)。您可以选择根据数据点的"平均"、"最大"、"最小"或"总和"或选定间隔内最后一次收集的数据点来聚合数据点。要选择聚合方法，请单击小工具查询部分中的 * 更多选项 * 。

允许的最小间隔为10分钟。较小的间隔加上较长的时间范围可能会导致"聚合间隔导致数据点太多"。 警告。如果间隔较小，则可能会看到此情况，并将信息板时间范围增加到 7 天。在这种情况下、Insight会将聚合间隔临时增加到1小时、直到您选择更短的时间范围为止。

您还可以在条形图小工具和单值小工具中聚合数据。

默认情况下，大多数资产计数器聚合到 _Avg_ 。默认情况下、某些计数器聚合到_Max_、_min_或_Sum_。例如，默认情况下，端口错误聚合到 _Sum_ ，其中存储 IOPS 聚合到 _Avg_ 。
