---
permalink: howto/expressions-example-system-i-o.html 
sidebar: sidebar 
keywords:  
summary: 通过表达式、您可以自由绘制可从其他指标计算的数据图表。 
---
= 表达式示例： "system" I/O
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通过表达式、您可以自由绘制可从其他指标计算的数据图表。



== 关于此任务

示例2：OnCommand Insight 从数据源获取许多指标。其中包括读取、写入和总IOPS。但是、通过采集报告的IOPS总数有时包括"系统"IOPS、而这些IOPS不是数据读取或写入的直接部分。此系统 I/O 也可视为 " 开销 " I/O ，这对于系统正常运行是必需的，但与数据操作没有直接关系。

要显示这些系统 I/O ，您可以从采集报告的总 IOPS 中减去读取和写入 IOPS 。公式可能如下所示：

* 系统IOPS =总IOPS -(读取IOPS +写入IOPS)


然后，这些数据可以显示在信息板上的折线图中。要执行此操作，请执行以下步骤：



== 步骤

. 创建新的信息板或以*编辑模式*打开现有信息板。
. 向信息板添加小工具。选择 * 折线图 * 。
+
此时，此小工具将以编辑模式打开。默认情况下、系统会显示一个查询、其中显示*存储*资产的* IOPS -总计*。如果需要，请选择其他资产类型。

. 单击按钮以创建查询的副本。
+
在原始查询下方添加一个查询副本。

. 在第二个查询中，单击 * 转换为表达式 * 按钮。
+
当前查询将转换为表达式模式。如果您希望随时切换回查询模式，请单击 * 还原至查询 * 。请注意，在不同模式之间切换会将字段重置为其默认值。

+
目前、请保持*表达式*模式。

. 现在、* IOPS -总计*指标位于字母变量字段"`a`"中。单击* IOPS -总计*并将其更改为* IOPS -读取*。。
. 在"`b`"变量字段中、单击*选择*、然后选择* IOPS -写入*。
. 在 * 表达式 * 字段中，您可以使用与每个变量对应的字母来构建表达式。我们将表达式简单地写为： `a + b`。在*显示*部分中、为此表达式选择"*分区图"*。
. * 标签 * 字段用于标识表达式。将此标签更改为"`Ssystem IOPS`"或对您同样有意义的内容。
+
此图表以折线图的形式显示总 IOPS ，下面是一个分区图，其中显示了读取和写入 IOPS 的组合。两者之间的差距显示了与数据读取或写入操作没有直接关系的 IOPS 。

. 单击 * 保存 * 将图表保存到信息板。

