---
permalink: howto/expressions-example-read-iops-percentage.html 
sidebar: sidebar 
keywords:  
summary: 使用表达式、您可以通过其他方式查看指标、例如占总数的百分比。 
---
= 表达式示例：读取IOPS百分比
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用表达式、您可以通过其他方式查看指标、例如占总数的百分比。



== 关于此任务

在此示例中、我们希望将读取IOPS显示为总IOPS的百分比。您可以将其视为以下公式：

* 读取百分比=(读取IOPS/总IOPS) x 100


这些数据可以显示在信息板上的折线图中。要执行此操作，请执行以下步骤：



== 步骤

. 创建新的信息板或以*编辑模式*打开现有信息板。
. 向信息板添加小工具。选择 * 分区图 * 。
+
此时，此小工具将以编辑模式打开。默认情况下、系统会显示一个查询、其中显示*存储*资产的* IOPS -总计*。如果需要，请选择其他资产类型。

. 单击*转换为表达式*按钮。
+
当前查询将转换为表达式模式。请注意，在表达式模式下无法更改资产类型。请注意、在表达式模式下、此按钮将更改为*还原到查询*。如果您希望随时切换回查询模式，请单击此按钮。请注意，在不同模式之间切换会将字段重置为其默认值。

+
目前、请保持*表达式*模式。

. 现在、* IOPS -总计*指标位于字母变量字段"`a`"中。在"`b`"变量字段中、单击*选择*、然后选择* IOPS - Read*。
+
通过单击变量字段后面的"++"*按钮、您最多可以为表达式添加五个字母变量。对于读取百分比示例、我们只需要总IOPS ("`a`")和读取IOPS ("`b`")。

. 在 * 表达式 * 字段中，您可以使用与每个变量对应的字母来构建表达式。我们知道_read percentage =(Read IOPS/ Total IOPS) x 100_、因此我们将此表达式写入为： `(b / a) * 100`
. * 标签 * 字段用于标识表达式。将此标签更改为"`Read Percentage`"或对您同样有意义的内容。
. 将*单元*字段更改为"`%`"或"`Percent`"。
+
此图表显示选定存储设备的 IOPS 读取百分比随时间的变化。如果需要，您可以设置筛选器或选择其他汇总方法。请注意、如果选择*求和*作为汇总方法、则所有百分比值将相加、这可能会高于100%。

. 单击 * 保存 * 将图表保存到信息板。
+
您也可以在*折线图*、*样条图*或*堆栈分区图*小工具中使用表达式。


