---
permalink: howto/how-to-troubleshoot-fibre-channel-bb-credit-0-errors.html 
sidebar: sidebar 
keywords:  
summary: '光纤通道使用缓冲区到缓冲区信用值(BB信用值)来控制传输流。从端口发送帧时、信用值会减少、而端口收到响应时、信用值会进行补充。如果端口中的BB信用未得到补充、则传输流可能会受到影响。端口需要内存或缓冲区来临时存储帧、直到帧按顺序组装并交付为止。缓冲区数是指端口可以存储的帧数、称为缓冲区信用值。' 
---
= 对光纤通道BB信用0错误进行故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
光纤通道使用缓冲区到缓冲区信用值(BB信用值)来控制传输流。从端口发送帧时、信用值会减少、而端口收到响应时、信用值会进行补充。如果端口中的BB信用未得到补充、则传输流可能会受到影响。端口需要内存或缓冲区来临时存储帧、直到帧按顺序组装并交付为止。缓冲区数是指端口可以存储的帧数、称为缓冲区信用值。

由于给定端口的可用信用值接近零、因此会出现一条错误警告、指出在达到零时端口将停止接收传输、并且在BB信用值得到补充之前不会恢复。

您可以通过Insight性能策略为以下端口指标设置阈值。

|===


 a| 
BB信用零—Rx



 a| 
取样期间接收缓冲区到缓冲区信用计数过渡到零的次数



 a| 
BB信用零—Tx



 a| 
在取样期间、缓冲区到缓冲区的传输信用计数过渡到零的次数



 a| 
BB信用零—总计



 a| 
此端口由于所连接端口的信用不足而不得不停止传输的次数



 a| 
BB信用零持续时间- Tx



 a| 
采样间隔内Tx BB信用值为零的时间(以毫秒为单位)

|===
BB信用错误可能是由以下某些情形引起的：

* 如果给定实施中的FC帧大小百分比很高、远远小于最大大小、则可能需要更多的BB信用值。
* 您的环境中的工作负载发生变化、可能会影响与其连接的端口或设备、例如存储节点。


您可以使用网络结构、交换机和端口资产页面监控光纤通道环境。端口资产页面提供有关资源、其拓扑(设备及其连接)、性能图表以及关联资源表的摘要信息。在对光纤通道问题进行故障排除时、每个端口资产的性能图表会很有用、因为它会显示选定最大贡献端口的流量。此外、端口资产页面还会在此图表中显示缓冲区到缓冲区信用指标和端口错误、Insight会为每个指标显示一个单独的性能图表。
