---
permalink: howto/more-on-dashboard-variables.html 
sidebar: sidebar 
keywords:  
summary: 信息板变量有多种类型，可以在不同的字段中使用，并且必须遵循命名规则。此处将介绍这些概念。 
---
= 有关信息板变量的更多信息
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
信息板变量有多种类型，可以在不同的字段中使用，并且必须遵循命名规则。此处将介绍这些概念。



== 变量类型

变量可以是以下类型之一：

* 文本 * ：字母数字字符串。这是默认变量类型。

* 数字 * ：数字或数字范围。

*布尔值*：用于值为True/False、Yes/No、0/1等的字段 对于布尔变量、选项包括_Yes_、_No_、_Nones_、_any_。

* 日期 * ：日期或日期范围。



== "`Generic`"变量

您可以通过单击*变量*按钮并选择上述类型之一来设置通用变量或通用变量。这些类型始终显示在下拉列表的顶部。此变量将被指定一个默认名称、例如"`$var1`"、并且不与特定标注或属性绑定。

通过配置通用变量、您可以在小工具中使用该变量来筛选此类型的_any_字段。例如、如果您有一个表小工具显示_Name_、_Alias_和_Vendor_(均为文本类型属性)、并且"`$var1`"是一个文本类型变量、则可以为小工具中的每个字段设置筛选器以使用$var1变量。您可以将其他小工具设置为对这些字段或任何文本字段使用 $var1 。

在信息板页面上、将$var1设置为一个值(例如"`NetApp`")将筛选_all_小工具中设置为使用该变量的字段的_all_。通过这种方式，您可以一次更新多个小工具，以根据需要突出显示所选的信息板数据。

由于通用变量可用于此类型的任何字段，因此您可以更改通用变量的名称，而无需更改其功能。

[NOTE]
====
所有变量都被视为"通用"变量、即使您为特定属性创建的变量也是如此、因为在为某个类型的任何属性或标注设置筛选器时、系统会显示此类型的所有已配置变量。但是、最佳实践是、如果要使用通用变量筛选多个字段中的值、请创建一个通用变量、如上面的_Name/Alias/Vendor_示例所示。

====


== 变量命名

变量名称：

* 必须始终以"`$`"作为前缀。配置变量时，系统会自动添加此变量。
* 不能包含任何特殊字符；仅允许使用字母 a-z 和数字 0-9 。
* 不能超过20个字符、包括"`$`"符号。
* 不区分大小写：$CityName和$CityName是相同的变量。
* 不能与现有变量名称相同。
* 不能仅为"`$`"符号。




== 使用变量的小工具

变量可用于以下小工具：

* 区域图表
* 条形图
* 盒形图
* 折线图
* 散点图
* 单值小工具
* 样条曲线图
* 堆积面积图
* 表小工具

